//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Dwg_SummaryInfo_Property : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Dwg_SummaryInfo_Property(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Dwg_SummaryInfo_Property obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Dwg_SummaryInfo_Property() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LibreDWGPINVOKE.delete_Dwg_SummaryInfo_Property(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string key {
    set {
      LibreDWGPINVOKE.Dwg_SummaryInfo_Property_key_set(swigCPtr, value);
    } 
    get {
      string ret = LibreDWGPINVOKE.Dwg_SummaryInfo_Property_key_get(swigCPtr);
      return ret;
    } 
  }

  public string value {
    set {
      LibreDWGPINVOKE.Dwg_SummaryInfo_Property_value_set(swigCPtr, value);
    } 
    get {
      string ret = LibreDWGPINVOKE.Dwg_SummaryInfo_Property_value_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_SummaryInfo_Property() : this(LibreDWGPINVOKE.new_Dwg_SummaryInfo_Property(), true) {
  }

}
