//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Dwg_LWPOLYLINE_width : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Dwg_LWPOLYLINE_width(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Dwg_LWPOLYLINE_width obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Dwg_LWPOLYLINE_width() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LibreDWGPINVOKE.delete_Dwg_LWPOLYLINE_width(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public double start {
    set {
      LibreDWGPINVOKE.Dwg_LWPOLYLINE_width_start_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_LWPOLYLINE_width_start_get(swigCPtr);
      return ret;
    } 
  }

  public double end {
    set {
      LibreDWGPINVOKE.Dwg_LWPOLYLINE_width_end_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_LWPOLYLINE_width_end_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_LWPOLYLINE_width() : this(LibreDWGPINVOKE.new_Dwg_LWPOLYLINE_width(), true) {
  }

}
