//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Dwg_Object_Entity : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Dwg_Object_Entity(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Dwg_Object_Entity obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Dwg_Object_Entity() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LibreDWGPINVOKE.delete_Dwg_Object_Entity(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public uint objid {
    set {
      LibreDWGPINVOKE.Dwg_Object_Entity_objid_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_Entity_objid_get(swigCPtr);
      return ret;
    } 
  }

  public _dwg_object_entity_tio tio {
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_Entity_tio_get(swigCPtr);
      _dwg_object_entity_tio ret = (cPtr == global::System.IntPtr.Zero) ? null : new _dwg_object_entity_tio(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Data dwg {
    set {
      LibreDWGPINVOKE.Dwg_Object_Entity_dwg_set(swigCPtr, Dwg_Data.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_Entity_dwg_get(swigCPtr);
      Dwg_Data ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Data(cPtr, false);
      return ret;
    } 
  }

  public uint num_eed {
    set {
      LibreDWGPINVOKE.Dwg_Object_Entity_num_eed_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_Entity_num_eed_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_Eed eed {
    set {
      LibreDWGPINVOKE.Dwg_Object_Entity_eed_set(swigCPtr, Dwg_Eed.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_Entity_eed_get(swigCPtr);
      Dwg_Eed ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Eed(cPtr, false);
      return ret;
    } 
  }

  public byte preview_exists {
    set {
      LibreDWGPINVOKE.Dwg_Object_Entity_preview_exists_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_Entity_preview_exists_get(swigCPtr);
      return ret;
    } 
  }

  public ulong preview_size {
    set {
      LibreDWGPINVOKE.Dwg_Object_Entity_preview_size_set(swigCPtr, value);
    } 
    get {
      ulong ret = LibreDWGPINVOKE.Dwg_Object_Entity_preview_size_get(swigCPtr);
      return ret;
    } 
  }

  public string preview {
    set {
      LibreDWGPINVOKE.Dwg_Object_Entity_preview_set(swigCPtr, value);
    } 
    get {
      string ret = LibreDWGPINVOKE.Dwg_Object_Entity_preview_get(swigCPtr);
      return ret;
    } 
  }

  public byte entmode {
    set {
      LibreDWGPINVOKE.Dwg_Object_Entity_entmode_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_Entity_entmode_get(swigCPtr);
      return ret;
    } 
  }

  public uint num_reactors {
    set {
      LibreDWGPINVOKE.Dwg_Object_Entity_num_reactors_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_Entity_num_reactors_get(swigCPtr);
      return ret;
    } 
  }

  public byte xdic_missing_flag {
    set {
      LibreDWGPINVOKE.Dwg_Object_Entity_xdic_missing_flag_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_Entity_xdic_missing_flag_get(swigCPtr);
      return ret;
    } 
  }

  public byte isbylayerlt {
    set {
      LibreDWGPINVOKE.Dwg_Object_Entity_isbylayerlt_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_Entity_isbylayerlt_get(swigCPtr);
      return ret;
    } 
  }

  public byte nolinks {
    set {
      LibreDWGPINVOKE.Dwg_Object_Entity_nolinks_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_Entity_nolinks_get(swigCPtr);
      return ret;
    } 
  }

  public byte has_ds_binary_data {
    set {
      LibreDWGPINVOKE.Dwg_Object_Entity_has_ds_binary_data_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_Entity_has_ds_binary_data_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_Color color {
    set {
      LibreDWGPINVOKE.Dwg_Object_Entity_color_set(swigCPtr, Dwg_Color.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_Entity_color_get(swigCPtr);
      Dwg_Color ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Color(cPtr, false);
      return ret;
    } 
  }

  public double ltype_scale {
    set {
      LibreDWGPINVOKE.Dwg_Object_Entity_ltype_scale_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_Object_Entity_ltype_scale_get(swigCPtr);
      return ret;
    } 
  }

  public byte ltype_flags {
    set {
      LibreDWGPINVOKE.Dwg_Object_Entity_ltype_flags_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_Entity_ltype_flags_get(swigCPtr);
      return ret;
    } 
  }

  public byte plotstyle_flags {
    set {
      LibreDWGPINVOKE.Dwg_Object_Entity_plotstyle_flags_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_Entity_plotstyle_flags_get(swigCPtr);
      return ret;
    } 
  }

  public byte material_flags {
    set {
      LibreDWGPINVOKE.Dwg_Object_Entity_material_flags_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_Entity_material_flags_get(swigCPtr);
      return ret;
    } 
  }

  public byte shadow_flags {
    set {
      LibreDWGPINVOKE.Dwg_Object_Entity_shadow_flags_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_Entity_shadow_flags_get(swigCPtr);
      return ret;
    } 
  }

  public byte has_full_visualstyle {
    set {
      LibreDWGPINVOKE.Dwg_Object_Entity_has_full_visualstyle_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_Entity_has_full_visualstyle_get(swigCPtr);
      return ret;
    } 
  }

  public byte has_face_visualstyle {
    set {
      LibreDWGPINVOKE.Dwg_Object_Entity_has_face_visualstyle_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_Entity_has_face_visualstyle_get(swigCPtr);
      return ret;
    } 
  }

  public byte has_edge_visualstyle {
    set {
      LibreDWGPINVOKE.Dwg_Object_Entity_has_edge_visualstyle_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_Entity_has_edge_visualstyle_get(swigCPtr);
      return ret;
    } 
  }

  public ushort invisible {
    set {
      LibreDWGPINVOKE.Dwg_Object_Entity_invisible_set(swigCPtr, value);
    } 
    get {
      ushort ret = LibreDWGPINVOKE.Dwg_Object_Entity_invisible_get(swigCPtr);
      return ret;
    } 
  }

  public byte linewt {
    set {
      LibreDWGPINVOKE.Dwg_Object_Entity_linewt_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_Entity_linewt_get(swigCPtr);
      return ret;
    } 
  }

  public byte flag_r11 {
    set {
      LibreDWGPINVOKE.Dwg_Object_Entity_flag_r11_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_Entity_flag_r11_get(swigCPtr);
      return ret;
    } 
  }

  public ushort kind_r11 {
    set {
      LibreDWGPINVOKE.Dwg_Object_Entity_kind_r11_set(swigCPtr, value);
    } 
    get {
      ushort ret = LibreDWGPINVOKE.Dwg_Object_Entity_kind_r11_get(swigCPtr);
      return ret;
    } 
  }

  public ushort opts_r11 {
    set {
      LibreDWGPINVOKE.Dwg_Object_Entity_opts_r11_set(swigCPtr, value);
    } 
    get {
      ushort ret = LibreDWGPINVOKE.Dwg_Object_Entity_opts_r11_get(swigCPtr);
      return ret;
    } 
  }

  public byte extra_r11 {
    set {
      LibreDWGPINVOKE.Dwg_Object_Entity_extra_r11_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_Entity_extra_r11_get(swigCPtr);
      return ret;
    } 
  }

  public ushort layer_r11 {
    set {
      LibreDWGPINVOKE.Dwg_Object_Entity_layer_r11_set(swigCPtr, value);
    } 
    get {
      ushort ret = LibreDWGPINVOKE.Dwg_Object_Entity_layer_r11_get(swigCPtr);
      return ret;
    } 
  }

  public byte color_r11 {
    set {
      LibreDWGPINVOKE.Dwg_Object_Entity_color_r11_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_Entity_color_r11_get(swigCPtr);
      return ret;
    } 
  }

  public ushort ltype_r11 {
    set {
      LibreDWGPINVOKE.Dwg_Object_Entity_ltype_r11_set(swigCPtr, value);
    } 
    get {
      ushort ret = LibreDWGPINVOKE.Dwg_Object_Entity_ltype_r11_get(swigCPtr);
      return ret;
    } 
  }

  public double elevation_r11 {
    set {
      LibreDWGPINVOKE.Dwg_Object_Entity_elevation_r11_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_Object_Entity_elevation_r11_get(swigCPtr);
      return ret;
    } 
  }

  public double thickness_r11 {
    set {
      LibreDWGPINVOKE.Dwg_Object_Entity_thickness_r11_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_Object_Entity_thickness_r11_get(swigCPtr);
      return ret;
    } 
  }

  public ushort paper_r11 {
    set {
      LibreDWGPINVOKE.Dwg_Object_Entity_paper_r11_set(swigCPtr, value);
    } 
    get {
      ushort ret = LibreDWGPINVOKE.Dwg_Object_Entity_paper_r11_get(swigCPtr);
      return ret;
    } 
  }

  public uint __iterator {
    set {
      LibreDWGPINVOKE.Dwg_Object_Entity___iterator_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_Entity___iterator_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_Object_Ref ownerhandle {
    set {
      LibreDWGPINVOKE.Dwg_Object_Entity_ownerhandle_set(swigCPtr, Dwg_Object_Ref.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_Entity_ownerhandle_get(swigCPtr);
      Dwg_Object_Ref ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Ref(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_p__dwg_object_ref reactors {
    set {
      LibreDWGPINVOKE.Dwg_Object_Entity_reactors_set(swigCPtr, SWIGTYPE_p_p__dwg_object_ref.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_Entity_reactors_get(swigCPtr);
      SWIGTYPE_p_p__dwg_object_ref ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p__dwg_object_ref(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Object_Ref xdicobjhandle {
    set {
      LibreDWGPINVOKE.Dwg_Object_Entity_xdicobjhandle_set(swigCPtr, Dwg_Object_Ref.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_Entity_xdicobjhandle_get(swigCPtr);
      Dwg_Object_Ref ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Ref(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Object_Ref prev_entity {
    set {
      LibreDWGPINVOKE.Dwg_Object_Entity_prev_entity_set(swigCPtr, Dwg_Object_Ref.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_Entity_prev_entity_get(swigCPtr);
      Dwg_Object_Ref ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Ref(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Object_Ref next_entity {
    set {
      LibreDWGPINVOKE.Dwg_Object_Entity_next_entity_set(swigCPtr, Dwg_Object_Ref.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_Entity_next_entity_get(swigCPtr);
      Dwg_Object_Ref ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Ref(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Object_Ref layer {
    set {
      LibreDWGPINVOKE.Dwg_Object_Entity_layer_set(swigCPtr, Dwg_Object_Ref.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_Entity_layer_get(swigCPtr);
      Dwg_Object_Ref ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Ref(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Object_Ref ltype {
    set {
      LibreDWGPINVOKE.Dwg_Object_Entity_ltype_set(swigCPtr, Dwg_Object_Ref.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_Entity_ltype_get(swigCPtr);
      Dwg_Object_Ref ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Ref(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Object_Ref material {
    set {
      LibreDWGPINVOKE.Dwg_Object_Entity_material_set(swigCPtr, Dwg_Object_Ref.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_Entity_material_get(swigCPtr);
      Dwg_Object_Ref ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Ref(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Object_Ref shadow {
    set {
      LibreDWGPINVOKE.Dwg_Object_Entity_shadow_set(swigCPtr, Dwg_Object_Ref.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_Entity_shadow_get(swigCPtr);
      Dwg_Object_Ref ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Ref(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Object_Ref plotstyle {
    set {
      LibreDWGPINVOKE.Dwg_Object_Entity_plotstyle_set(swigCPtr, Dwg_Object_Ref.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_Entity_plotstyle_get(swigCPtr);
      Dwg_Object_Ref ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Ref(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Object_Ref full_visualstyle {
    set {
      LibreDWGPINVOKE.Dwg_Object_Entity_full_visualstyle_set(swigCPtr, Dwg_Object_Ref.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_Entity_full_visualstyle_get(swigCPtr);
      Dwg_Object_Ref ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Ref(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Object_Ref face_visualstyle {
    set {
      LibreDWGPINVOKE.Dwg_Object_Entity_face_visualstyle_set(swigCPtr, Dwg_Object_Ref.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_Entity_face_visualstyle_get(swigCPtr);
      Dwg_Object_Ref ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Ref(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Object_Ref edge_visualstyle {
    set {
      LibreDWGPINVOKE.Dwg_Object_Entity_edge_visualstyle_set(swigCPtr, Dwg_Object_Ref.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_Entity_edge_visualstyle_get(swigCPtr);
      Dwg_Object_Ref ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Ref(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Object_Entity() : this(LibreDWGPINVOKE.new_Dwg_Object_Entity(), true) {
  }

}
