//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Dwg_Data : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Dwg_Data(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Dwg_Data obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Dwg_Data() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LibreDWGPINVOKE.delete_Dwg_Data(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Dwg_Header header {
    set {
      LibreDWGPINVOKE.Dwg_Data_header_set(swigCPtr, Dwg_Header.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Data_header_get(swigCPtr);
      Dwg_Header ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Header(cPtr, false);
      return ret;
    } 
  }

  public Dwg_R2004_Header r2004_header {
    set {
      LibreDWGPINVOKE.Dwg_Data_r2004_header_set(swigCPtr, Dwg_R2004_Header.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Data_r2004_header_get(swigCPtr);
      Dwg_R2004_Header ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_R2004_Header(cPtr, false);
      return ret;
    } 
  }

  public Dwg_AuxHeader auxheader {
    set {
      LibreDWGPINVOKE.Dwg_Data_auxheader_set(swigCPtr, Dwg_AuxHeader.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Data_auxheader_get(swigCPtr);
      Dwg_AuxHeader ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_AuxHeader(cPtr, false);
      return ret;
    } 
  }

  public Dwg_SummaryInfo summaryinfo {
    set {
      LibreDWGPINVOKE.Dwg_Data_summaryinfo_set(swigCPtr, Dwg_SummaryInfo.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Data_summaryinfo_get(swigCPtr);
      Dwg_SummaryInfo ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_SummaryInfo(cPtr, false);
      return ret;
    } 
  }

  public _dwg_second_header second_header {
    set {
      LibreDWGPINVOKE.Dwg_Data_second_header_set(swigCPtr, _dwg_second_header.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Data_second_header_get(swigCPtr);
      _dwg_second_header ret = (cPtr == global::System.IntPtr.Zero) ? null : new _dwg_second_header(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Chain thumbnail {
    set {
      LibreDWGPINVOKE.Dwg_Data_thumbnail_set(swigCPtr, Dwg_Chain.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Data_thumbnail_get(swigCPtr);
      Dwg_Chain ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Chain(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Header_Variables header_vars {
    set {
      LibreDWGPINVOKE.Dwg_Data_header_vars_set(swigCPtr, Dwg_Header_Variables.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Data_header_vars_get(swigCPtr);
      Dwg_Header_Variables ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Header_Variables(cPtr, false);
      return ret;
    } 
  }

  public ushort num_classes {
    set {
      LibreDWGPINVOKE.Dwg_Data_num_classes_set(swigCPtr, value);
    } 
    get {
      ushort ret = LibreDWGPINVOKE.Dwg_Data_num_classes_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_Class dwg_class {
    set {
      LibreDWGPINVOKE.Dwg_Data_dwg_class_set(swigCPtr, Dwg_Class.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Data_dwg_class_get(swigCPtr);
      Dwg_Class ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Class(cPtr, false);
      return ret;
    } 
  }

  public uint num_objects {
    set {
      LibreDWGPINVOKE.Dwg_Data_num_objects_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Data_num_objects_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_Object object_ {
    set {
      LibreDWGPINVOKE.Dwg_Data_object__set(swigCPtr, Dwg_Object.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Data_object__get(swigCPtr);
      Dwg_Object ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object(cPtr, false);
      return ret;
    } 
  }

  public uint num_entities {
    set {
      LibreDWGPINVOKE.Dwg_Data_num_entities_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Data_num_entities_get(swigCPtr);
      return ret;
    } 
  }

  public uint num_object_refs {
    set {
      LibreDWGPINVOKE.Dwg_Data_num_object_refs_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Data_num_object_refs_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_p__dwg_object_ref object_ref {
    set {
      LibreDWGPINVOKE.Dwg_Data_object_ref_set(swigCPtr, SWIGTYPE_p_p__dwg_object_ref.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Data_object_ref_get(swigCPtr);
      SWIGTYPE_p_p__dwg_object_ref ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p__dwg_object_ref(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p__inthash object_map {
    set {
      LibreDWGPINVOKE.Dwg_Data_object_map_set(swigCPtr, SWIGTYPE_p__inthash.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Data_object_map_get(swigCPtr);
      SWIGTYPE_p__inthash ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p__inthash(cPtr, false);
      return ret;
    } 
  }

  public int dirty_refs {
    set {
      LibreDWGPINVOKE.Dwg_Data_dirty_refs_set(swigCPtr, value);
    } 
    get {
      int ret = LibreDWGPINVOKE.Dwg_Data_dirty_refs_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_Object mspace_block {
    set {
      LibreDWGPINVOKE.Dwg_Data_mspace_block_set(swigCPtr, Dwg_Object.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Data_mspace_block_get(swigCPtr);
      Dwg_Object ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Object pspace_block {
    set {
      LibreDWGPINVOKE.Dwg_Data_pspace_block_set(swigCPtr, Dwg_Object.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Data_pspace_block_get(swigCPtr);
      Dwg_Object ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Object_BLOCK_CONTROL block_control {
    set {
      LibreDWGPINVOKE.Dwg_Data_block_control_set(swigCPtr, Dwg_Object_BLOCK_CONTROL.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Data_block_control_get(swigCPtr);
      Dwg_Object_BLOCK_CONTROL ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_BLOCK_CONTROL(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Object_LAYER_CONTROL layer_control {
    set {
      LibreDWGPINVOKE.Dwg_Data_layer_control_set(swigCPtr, Dwg_Object_LAYER_CONTROL.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Data_layer_control_get(swigCPtr);
      Dwg_Object_LAYER_CONTROL ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_LAYER_CONTROL(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Object_STYLE_CONTROL style_control {
    set {
      LibreDWGPINVOKE.Dwg_Data_style_control_set(swigCPtr, Dwg_Object_STYLE_CONTROL.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Data_style_control_get(swigCPtr);
      Dwg_Object_STYLE_CONTROL ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_STYLE_CONTROL(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Object_LTYPE_CONTROL ltype_control {
    set {
      LibreDWGPINVOKE.Dwg_Data_ltype_control_set(swigCPtr, Dwg_Object_LTYPE_CONTROL.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Data_ltype_control_get(swigCPtr);
      Dwg_Object_LTYPE_CONTROL ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_LTYPE_CONTROL(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Object_VIEW_CONTROL view_control {
    set {
      LibreDWGPINVOKE.Dwg_Data_view_control_set(swigCPtr, Dwg_Object_VIEW_CONTROL.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Data_view_control_get(swigCPtr);
      Dwg_Object_VIEW_CONTROL ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_VIEW_CONTROL(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Object_UCS_CONTROL ucs_control {
    set {
      LibreDWGPINVOKE.Dwg_Data_ucs_control_set(swigCPtr, Dwg_Object_UCS_CONTROL.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Data_ucs_control_get(swigCPtr);
      Dwg_Object_UCS_CONTROL ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_UCS_CONTROL(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Object_VPORT_CONTROL vport_control {
    set {
      LibreDWGPINVOKE.Dwg_Data_vport_control_set(swigCPtr, Dwg_Object_VPORT_CONTROL.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Data_vport_control_get(swigCPtr);
      Dwg_Object_VPORT_CONTROL ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_VPORT_CONTROL(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Object_APPID_CONTROL appid_control {
    set {
      LibreDWGPINVOKE.Dwg_Data_appid_control_set(swigCPtr, Dwg_Object_APPID_CONTROL.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Data_appid_control_get(swigCPtr);
      Dwg_Object_APPID_CONTROL ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_APPID_CONTROL(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Object_DIMSTYLE_CONTROL dimstyle_control {
    set {
      LibreDWGPINVOKE.Dwg_Data_dimstyle_control_set(swigCPtr, Dwg_Object_DIMSTYLE_CONTROL.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Data_dimstyle_control_get(swigCPtr);
      Dwg_Object_DIMSTYLE_CONTROL ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_DIMSTYLE_CONTROL(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Object_VPORT_ENTITY_CONTROL vport_entity_control {
    set {
      LibreDWGPINVOKE.Dwg_Data_vport_entity_control_set(swigCPtr, Dwg_Object_VPORT_ENTITY_CONTROL.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Data_vport_entity_control_get(swigCPtr);
      Dwg_Object_VPORT_ENTITY_CONTROL ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_VPORT_ENTITY_CONTROL(cPtr, false);
      return ret;
    } 
  }

  public uint layout_type {
    set {
      LibreDWGPINVOKE.Dwg_Data_layout_type_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Data_layout_type_get(swigCPtr);
      return ret;
    } 
  }

  public uint opts {
    set {
      LibreDWGPINVOKE.Dwg_Data_opts_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Data_opts_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_Data() : this(LibreDWGPINVOKE.new_Dwg_Data(), true) {
  }

}
