//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Dwg_Object_MATERIAL : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Dwg_Object_MATERIAL(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Dwg_Object_MATERIAL obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Dwg_Object_MATERIAL() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LibreDWGPINVOKE.delete_Dwg_Object_MATERIAL(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Dwg_Object_Object parent {
    set {
      LibreDWGPINVOKE.Dwg_Object_MATERIAL_parent_set(swigCPtr, Dwg_Object_Object.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_MATERIAL_parent_get(swigCPtr);
      Dwg_Object_Object ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Object(cPtr, false);
      return ret;
    } 
  }

  public string name {
    set {
      LibreDWGPINVOKE.Dwg_Object_MATERIAL_name_set(swigCPtr, value);
    } 
    get {
      string ret = LibreDWGPINVOKE.Dwg_Object_MATERIAL_name_get(swigCPtr);
      return ret;
    } 
  }

  public string description {
    set {
      LibreDWGPINVOKE.Dwg_Object_MATERIAL_description_set(swigCPtr, value);
    } 
    get {
      string ret = LibreDWGPINVOKE.Dwg_Object_MATERIAL_description_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_MATERIAL_color ambient_color {
    set {
      LibreDWGPINVOKE.Dwg_Object_MATERIAL_ambient_color_set(swigCPtr, Dwg_MATERIAL_color.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_MATERIAL_ambient_color_get(swigCPtr);
      Dwg_MATERIAL_color ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_MATERIAL_color(cPtr, false);
      return ret;
    } 
  }

  public Dwg_MATERIAL_color diffuse_color {
    set {
      LibreDWGPINVOKE.Dwg_Object_MATERIAL_diffuse_color_set(swigCPtr, Dwg_MATERIAL_color.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_MATERIAL_diffuse_color_get(swigCPtr);
      Dwg_MATERIAL_color ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_MATERIAL_color(cPtr, false);
      return ret;
    } 
  }

  public Dwg_MATERIAL_mapper diffusemap {
    set {
      LibreDWGPINVOKE.Dwg_Object_MATERIAL_diffusemap_set(swigCPtr, Dwg_MATERIAL_mapper.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_MATERIAL_diffusemap_get(swigCPtr);
      Dwg_MATERIAL_mapper ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_MATERIAL_mapper(cPtr, false);
      return ret;
    } 
  }

  public double specular_gloss_factor {
    set {
      LibreDWGPINVOKE.Dwg_Object_MATERIAL_specular_gloss_factor_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_Object_MATERIAL_specular_gloss_factor_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_MATERIAL_color specular_color {
    set {
      LibreDWGPINVOKE.Dwg_Object_MATERIAL_specular_color_set(swigCPtr, Dwg_MATERIAL_color.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_MATERIAL_specular_color_get(swigCPtr);
      Dwg_MATERIAL_color ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_MATERIAL_color(cPtr, false);
      return ret;
    } 
  }

  public Dwg_MATERIAL_mapper specularmap {
    set {
      LibreDWGPINVOKE.Dwg_Object_MATERIAL_specularmap_set(swigCPtr, Dwg_MATERIAL_mapper.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_MATERIAL_specularmap_get(swigCPtr);
      Dwg_MATERIAL_mapper ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_MATERIAL_mapper(cPtr, false);
      return ret;
    } 
  }

  public Dwg_MATERIAL_mapper reflectionmap {
    set {
      LibreDWGPINVOKE.Dwg_Object_MATERIAL_reflectionmap_set(swigCPtr, Dwg_MATERIAL_mapper.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_MATERIAL_reflectionmap_get(swigCPtr);
      Dwg_MATERIAL_mapper ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_MATERIAL_mapper(cPtr, false);
      return ret;
    } 
  }

  public double opacity_percent {
    set {
      LibreDWGPINVOKE.Dwg_Object_MATERIAL_opacity_percent_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_Object_MATERIAL_opacity_percent_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_MATERIAL_mapper opacitymap {
    set {
      LibreDWGPINVOKE.Dwg_Object_MATERIAL_opacitymap_set(swigCPtr, Dwg_MATERIAL_mapper.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_MATERIAL_opacitymap_get(swigCPtr);
      Dwg_MATERIAL_mapper ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_MATERIAL_mapper(cPtr, false);
      return ret;
    } 
  }

  public Dwg_MATERIAL_mapper bumpmap {
    set {
      LibreDWGPINVOKE.Dwg_Object_MATERIAL_bumpmap_set(swigCPtr, Dwg_MATERIAL_mapper.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_MATERIAL_bumpmap_get(swigCPtr);
      Dwg_MATERIAL_mapper ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_MATERIAL_mapper(cPtr, false);
      return ret;
    } 
  }

  public double refraction_index {
    set {
      LibreDWGPINVOKE.Dwg_Object_MATERIAL_refraction_index_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_Object_MATERIAL_refraction_index_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_MATERIAL_mapper refractionmap {
    set {
      LibreDWGPINVOKE.Dwg_Object_MATERIAL_refractionmap_set(swigCPtr, Dwg_MATERIAL_mapper.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_MATERIAL_refractionmap_get(swigCPtr);
      Dwg_MATERIAL_mapper ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_MATERIAL_mapper(cPtr, false);
      return ret;
    } 
  }

  public double color_bleed_scale {
    set {
      LibreDWGPINVOKE.Dwg_Object_MATERIAL_color_bleed_scale_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_Object_MATERIAL_color_bleed_scale_get(swigCPtr);
      return ret;
    } 
  }

  public double indirect_bump_scale {
    set {
      LibreDWGPINVOKE.Dwg_Object_MATERIAL_indirect_bump_scale_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_Object_MATERIAL_indirect_bump_scale_get(swigCPtr);
      return ret;
    } 
  }

  public double reflectance_scale {
    set {
      LibreDWGPINVOKE.Dwg_Object_MATERIAL_reflectance_scale_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_Object_MATERIAL_reflectance_scale_get(swigCPtr);
      return ret;
    } 
  }

  public double transmittance_scale {
    set {
      LibreDWGPINVOKE.Dwg_Object_MATERIAL_transmittance_scale_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_Object_MATERIAL_transmittance_scale_get(swigCPtr);
      return ret;
    } 
  }

  public byte two_sided_material {
    set {
      LibreDWGPINVOKE.Dwg_Object_MATERIAL_two_sided_material_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_MATERIAL_two_sided_material_get(swigCPtr);
      return ret;
    } 
  }

  public double luminance {
    set {
      LibreDWGPINVOKE.Dwg_Object_MATERIAL_luminance_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_Object_MATERIAL_luminance_get(swigCPtr);
      return ret;
    } 
  }

  public ushort luminance_mode {
    set {
      LibreDWGPINVOKE.Dwg_Object_MATERIAL_luminance_mode_set(swigCPtr, value);
    } 
    get {
      ushort ret = LibreDWGPINVOKE.Dwg_Object_MATERIAL_luminance_mode_get(swigCPtr);
      return ret;
    } 
  }

  public double translucence {
    set {
      LibreDWGPINVOKE.Dwg_Object_MATERIAL_translucence_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_Object_MATERIAL_translucence_get(swigCPtr);
      return ret;
    } 
  }

  public double self_illumination {
    set {
      LibreDWGPINVOKE.Dwg_Object_MATERIAL_self_illumination_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_Object_MATERIAL_self_illumination_get(swigCPtr);
      return ret;
    } 
  }

  public double reflectivity {
    set {
      LibreDWGPINVOKE.Dwg_Object_MATERIAL_reflectivity_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_Object_MATERIAL_reflectivity_get(swigCPtr);
      return ret;
    } 
  }

  public uint illumination_model {
    set {
      LibreDWGPINVOKE.Dwg_Object_MATERIAL_illumination_model_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_MATERIAL_illumination_model_get(swigCPtr);
      return ret;
    } 
  }

  public uint channel_flags {
    set {
      LibreDWGPINVOKE.Dwg_Object_MATERIAL_channel_flags_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_MATERIAL_channel_flags_get(swigCPtr);
      return ret;
    } 
  }

  public uint mode {
    set {
      LibreDWGPINVOKE.Dwg_Object_MATERIAL_mode_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_MATERIAL_mode_get(swigCPtr);
      return ret;
    } 
  }

  public string genprocname {
    set {
      LibreDWGPINVOKE.Dwg_Object_MATERIAL_genprocname_set(swigCPtr, value);
    } 
    get {
      string ret = LibreDWGPINVOKE.Dwg_Object_MATERIAL_genprocname_get(swigCPtr);
      return ret;
    } 
  }

  public ushort genproctype {
    set {
      LibreDWGPINVOKE.Dwg_Object_MATERIAL_genproctype_set(swigCPtr, value);
    } 
    get {
      ushort ret = LibreDWGPINVOKE.Dwg_Object_MATERIAL_genproctype_get(swigCPtr);
      return ret;
    } 
  }

  public byte genprocvalbool {
    set {
      LibreDWGPINVOKE.Dwg_Object_MATERIAL_genprocvalbool_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_MATERIAL_genprocvalbool_get(swigCPtr);
      return ret;
    } 
  }

  public ushort genprocvalint {
    set {
      LibreDWGPINVOKE.Dwg_Object_MATERIAL_genprocvalint_set(swigCPtr, value);
    } 
    get {
      ushort ret = LibreDWGPINVOKE.Dwg_Object_MATERIAL_genprocvalint_get(swigCPtr);
      return ret;
    } 
  }

  public double genprocvalreal {
    set {
      LibreDWGPINVOKE.Dwg_Object_MATERIAL_genprocvalreal_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_Object_MATERIAL_genprocvalreal_get(swigCPtr);
      return ret;
    } 
  }

  public string genprocvaltext {
    set {
      LibreDWGPINVOKE.Dwg_Object_MATERIAL_genprocvaltext_set(swigCPtr, value);
    } 
    get {
      string ret = LibreDWGPINVOKE.Dwg_Object_MATERIAL_genprocvaltext_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_Color genprocvalcolor {
    set {
      LibreDWGPINVOKE.Dwg_Object_MATERIAL_genprocvalcolor_set(swigCPtr, Dwg_Color.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_MATERIAL_genprocvalcolor_get(swigCPtr);
      Dwg_Color ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Color(cPtr, false);
      return ret;
    } 
  }

  public byte genproctableend {
    set {
      LibreDWGPINVOKE.Dwg_Object_MATERIAL_genproctableend_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_MATERIAL_genproctableend_get(swigCPtr);
      return ret;
    } 
  }

  public ushort num_gentextures {
    set {
      LibreDWGPINVOKE.Dwg_Object_MATERIAL_num_gentextures_set(swigCPtr, value);
    } 
    get {
      ushort ret = LibreDWGPINVOKE.Dwg_Object_MATERIAL_num_gentextures_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_MATERIAL_gentexture gentextures {
    set {
      LibreDWGPINVOKE.Dwg_Object_MATERIAL_gentextures_set(swigCPtr, Dwg_MATERIAL_gentexture.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_MATERIAL_gentextures_get(swigCPtr);
      Dwg_MATERIAL_gentexture ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_MATERIAL_gentexture(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Object_MATERIAL() : this(LibreDWGPINVOKE.new_Dwg_Object_MATERIAL(), true) {
  }

}
