//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Dwg_SPLINE_point : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Dwg_SPLINE_point(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Dwg_SPLINE_point obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Dwg_SPLINE_point() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LibreDWGPINVOKE.delete_Dwg_SPLINE_point(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Dwg_Entity_SPLINE parent {
    set {
      LibreDWGPINVOKE.Dwg_SPLINE_point_parent_set(swigCPtr, Dwg_Entity_SPLINE.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_SPLINE_point_parent_get(swigCPtr);
      Dwg_Entity_SPLINE ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Entity_SPLINE(cPtr, false);
      return ret;
    } 
  }

  public double x {
    set {
      LibreDWGPINVOKE.Dwg_SPLINE_point_x_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_SPLINE_point_x_get(swigCPtr);
      return ret;
    } 
  }

  public double y {
    set {
      LibreDWGPINVOKE.Dwg_SPLINE_point_y_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_SPLINE_point_y_get(swigCPtr);
      return ret;
    } 
  }

  public double z {
    set {
      LibreDWGPINVOKE.Dwg_SPLINE_point_z_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_SPLINE_point_z_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_SPLINE_point() : this(LibreDWGPINVOKE.new_Dwg_SPLINE_point(), true) {
  }

}
