//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Dwg_LEADER_BlockLabel : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Dwg_LEADER_BlockLabel(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Dwg_LEADER_BlockLabel obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Dwg_LEADER_BlockLabel() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LibreDWGPINVOKE.delete_Dwg_LEADER_BlockLabel(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Dwg_Entity_MULTILEADER parent {
    set {
      LibreDWGPINVOKE.Dwg_LEADER_BlockLabel_parent_set(swigCPtr, Dwg_Entity_MULTILEADER.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_LEADER_BlockLabel_parent_get(swigCPtr);
      Dwg_Entity_MULTILEADER ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Entity_MULTILEADER(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Object_Ref attdef {
    set {
      LibreDWGPINVOKE.Dwg_LEADER_BlockLabel_attdef_set(swigCPtr, Dwg_Object_Ref.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_LEADER_BlockLabel_attdef_get(swigCPtr);
      Dwg_Object_Ref ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Ref(cPtr, false);
      return ret;
    } 
  }

  public string label_text {
    set {
      LibreDWGPINVOKE.Dwg_LEADER_BlockLabel_label_text_set(swigCPtr, value);
    } 
    get {
      string ret = LibreDWGPINVOKE.Dwg_LEADER_BlockLabel_label_text_get(swigCPtr);
      return ret;
    } 
  }

  public ushort ui_index {
    set {
      LibreDWGPINVOKE.Dwg_LEADER_BlockLabel_ui_index_set(swigCPtr, value);
    } 
    get {
      ushort ret = LibreDWGPINVOKE.Dwg_LEADER_BlockLabel_ui_index_get(swigCPtr);
      return ret;
    } 
  }

  public double width {
    set {
      LibreDWGPINVOKE.Dwg_LEADER_BlockLabel_width_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_LEADER_BlockLabel_width_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_LEADER_BlockLabel() : this(LibreDWGPINVOKE.new_Dwg_LEADER_BlockLabel(), true) {
  }

}
