//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Dwg_AcDs_DataIndex : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Dwg_AcDs_DataIndex(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Dwg_AcDs_DataIndex obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Dwg_AcDs_DataIndex() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LibreDWGPINVOKE.delete_Dwg_AcDs_DataIndex(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public uint num_entries {
    set {
      LibreDWGPINVOKE.Dwg_AcDs_DataIndex_num_entries_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_AcDs_DataIndex_num_entries_get(swigCPtr);
      return ret;
    } 
  }

  public uint di_unknown {
    set {
      LibreDWGPINVOKE.Dwg_AcDs_DataIndex_di_unknown_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_AcDs_DataIndex_di_unknown_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_AcDs_DataIndex_Entry entries {
    set {
      LibreDWGPINVOKE.Dwg_AcDs_DataIndex_entries_set(swigCPtr, Dwg_AcDs_DataIndex_Entry.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_AcDs_DataIndex_entries_get(swigCPtr);
      Dwg_AcDs_DataIndex_Entry ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_AcDs_DataIndex_Entry(cPtr, false);
      return ret;
    } 
  }

  public Dwg_AcDs_DataIndex() : this(LibreDWGPINVOKE.new_Dwg_AcDs_DataIndex(), true) {
  }

}
