//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Dwg_CELLSTYLEMAP_Cell : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Dwg_CELLSTYLEMAP_Cell(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Dwg_CELLSTYLEMAP_Cell obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Dwg_CELLSTYLEMAP_Cell() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LibreDWGPINVOKE.delete_Dwg_CELLSTYLEMAP_Cell(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Dwg_Object_CELLSTYLEMAP parent {
    set {
      LibreDWGPINVOKE.Dwg_CELLSTYLEMAP_Cell_parent_set(swigCPtr, Dwg_Object_CELLSTYLEMAP.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_CELLSTYLEMAP_Cell_parent_get(swigCPtr);
      Dwg_Object_CELLSTYLEMAP ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_CELLSTYLEMAP(cPtr, false);
      return ret;
    } 
  }

  public Dwg_CellStyle style {
    set {
      LibreDWGPINVOKE.Dwg_CELLSTYLEMAP_Cell_style_set(swigCPtr, Dwg_CellStyle.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_CELLSTYLEMAP_Cell_style_get(swigCPtr);
      Dwg_CellStyle ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_CellStyle(cPtr, false);
      return ret;
    } 
  }

  public uint id {
    set {
      LibreDWGPINVOKE.Dwg_CELLSTYLEMAP_Cell_id_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_CELLSTYLEMAP_Cell_id_get(swigCPtr);
      return ret;
    } 
  }

  public uint type {
    set {
      LibreDWGPINVOKE.Dwg_CELLSTYLEMAP_Cell_type_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_CELLSTYLEMAP_Cell_type_get(swigCPtr);
      return ret;
    } 
  }

  public string name {
    set {
      LibreDWGPINVOKE.Dwg_CELLSTYLEMAP_Cell_name_set(swigCPtr, value);
    } 
    get {
      string ret = LibreDWGPINVOKE.Dwg_CELLSTYLEMAP_Cell_name_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_CELLSTYLEMAP_Cell() : this(LibreDWGPINVOKE.new_Dwg_CELLSTYLEMAP_Cell(), true) {
  }

}
