//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Dwg_Object_ASSOCALIGNEDDIMACTIONBODY : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Dwg_Object_ASSOCALIGNEDDIMACTIONBODY(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Dwg_Object_ASSOCALIGNEDDIMACTIONBODY obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Dwg_Object_ASSOCALIGNEDDIMACTIONBODY() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LibreDWGPINVOKE.delete_Dwg_Object_ASSOCALIGNEDDIMACTIONBODY(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Dwg_Object_Object parent {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCALIGNEDDIMACTIONBODY_parent_set(swigCPtr, Dwg_Object_Object.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_ASSOCALIGNEDDIMACTIONBODY_parent_get(swigCPtr);
      Dwg_Object_Object ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Object(cPtr, false);
      return ret;
    } 
  }

  public uint aab_status {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCALIGNEDDIMACTIONBODY_aab_status_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_ASSOCALIGNEDDIMACTIONBODY_aab_status_get(swigCPtr);
      return ret;
    } 
  }

  public uint pab_status {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCALIGNEDDIMACTIONBODY_pab_status_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_ASSOCALIGNEDDIMACTIONBODY_pab_status_get(swigCPtr);
      return ret;
    } 
  }

  public uint pab_l2 {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCALIGNEDDIMACTIONBODY_pab_l2_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_ASSOCALIGNEDDIMACTIONBODY_pab_l2_get(swigCPtr);
      return ret;
    } 
  }

  public uint pab_l3 {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCALIGNEDDIMACTIONBODY_pab_l3_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_ASSOCALIGNEDDIMACTIONBODY_pab_l3_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_Object_Ref writedep {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCALIGNEDDIMACTIONBODY_writedep_set(swigCPtr, Dwg_Object_Ref.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_ASSOCALIGNEDDIMACTIONBODY_writedep_get(swigCPtr);
      Dwg_Object_Ref ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Ref(cPtr, false);
      return ret;
    } 
  }

  public uint pab_l4 {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCALIGNEDDIMACTIONBODY_pab_l4_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_ASSOCALIGNEDDIMACTIONBODY_pab_l4_get(swigCPtr);
      return ret;
    } 
  }

  public uint pab_l5 {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCALIGNEDDIMACTIONBODY_pab_l5_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_ASSOCALIGNEDDIMACTIONBODY_pab_l5_get(swigCPtr);
      return ret;
    } 
  }

  public uint pab_l6 {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCALIGNEDDIMACTIONBODY_pab_l6_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_ASSOCALIGNEDDIMACTIONBODY_pab_l6_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_Object_Ref readdep {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCALIGNEDDIMACTIONBODY_readdep_set(swigCPtr, Dwg_Object_Ref.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_ASSOCALIGNEDDIMACTIONBODY_readdep_get(swigCPtr);
      Dwg_Object_Ref ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Ref(cPtr, false);
      return ret;
    } 
  }

  public uint dcm_status {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCALIGNEDDIMACTIONBODY_dcm_status_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_ASSOCALIGNEDDIMACTIONBODY_dcm_status_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_Object_Ref d_node {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCALIGNEDDIMACTIONBODY_d_node_set(swigCPtr, Dwg_Object_Ref.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_ASSOCALIGNEDDIMACTIONBODY_d_node_get(swigCPtr);
      Dwg_Object_Ref ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Ref(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Object_Ref r_node {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCALIGNEDDIMACTIONBODY_r_node_set(swigCPtr, Dwg_Object_Ref.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_ASSOCALIGNEDDIMACTIONBODY_r_node_get(swigCPtr);
      Dwg_Object_Ref ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Ref(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Object_ASSOCALIGNEDDIMACTIONBODY() : this(LibreDWGPINVOKE.new_Dwg_Object_ASSOCALIGNEDDIMACTIONBODY(), true) {
  }

}
