//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Dwg_Object_LEADEROBJECTCONTEXTDATA : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Dwg_Object_LEADEROBJECTCONTEXTDATA(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Dwg_Object_LEADEROBJECTCONTEXTDATA obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Dwg_Object_LEADEROBJECTCONTEXTDATA() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LibreDWGPINVOKE.delete_Dwg_Object_LEADEROBJECTCONTEXTDATA(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Dwg_Object_Object parent {
    set {
      LibreDWGPINVOKE.Dwg_Object_LEADEROBJECTCONTEXTDATA_parent_set(swigCPtr, Dwg_Object_Object.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_LEADEROBJECTCONTEXTDATA_parent_get(swigCPtr);
      Dwg_Object_Object ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Object(cPtr, false);
      return ret;
    } 
  }

  public ushort class_version {
    set {
      LibreDWGPINVOKE.Dwg_Object_LEADEROBJECTCONTEXTDATA_class_version_set(swigCPtr, value);
    } 
    get {
      ushort ret = LibreDWGPINVOKE.Dwg_Object_LEADEROBJECTCONTEXTDATA_class_version_get(swigCPtr);
      return ret;
    } 
  }

  public byte is_default {
    set {
      LibreDWGPINVOKE.Dwg_Object_LEADEROBJECTCONTEXTDATA_is_default_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_LEADEROBJECTCONTEXTDATA_is_default_get(swigCPtr);
      return ret;
    } 
  }

  public byte in_dwg {
    set {
      LibreDWGPINVOKE.Dwg_Object_LEADEROBJECTCONTEXTDATA_in_dwg_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_LEADEROBJECTCONTEXTDATA_in_dwg_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_Object_Ref scale {
    set {
      LibreDWGPINVOKE.Dwg_Object_LEADEROBJECTCONTEXTDATA_scale_set(swigCPtr, Dwg_Object_Ref.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_LEADEROBJECTCONTEXTDATA_scale_get(swigCPtr);
      Dwg_Object_Ref ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Ref(cPtr, false);
      return ret;
    } 
  }

  public uint num_points {
    set {
      LibreDWGPINVOKE.Dwg_Object_LEADEROBJECTCONTEXTDATA_num_points_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_LEADEROBJECTCONTEXTDATA_num_points_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_Bitcode_3BD points {
    set {
      LibreDWGPINVOKE.Dwg_Object_LEADEROBJECTCONTEXTDATA_points_set(swigCPtr, Dwg_Bitcode_3BD.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_LEADEROBJECTCONTEXTDATA_points_get(swigCPtr);
      Dwg_Bitcode_3BD ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Bitcode_3BD(cPtr, false);
      return ret;
    } 
  }

  public byte b290 {
    set {
      LibreDWGPINVOKE.Dwg_Object_LEADEROBJECTCONTEXTDATA_b290_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_LEADEROBJECTCONTEXTDATA_b290_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_Bitcode_3BD x_direction {
    set {
      LibreDWGPINVOKE.Dwg_Object_LEADEROBJECTCONTEXTDATA_x_direction_set(swigCPtr, Dwg_Bitcode_3BD.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_LEADEROBJECTCONTEXTDATA_x_direction_get(swigCPtr);
      Dwg_Bitcode_3BD ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Bitcode_3BD(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Bitcode_3BD inspt_offset {
    set {
      LibreDWGPINVOKE.Dwg_Object_LEADEROBJECTCONTEXTDATA_inspt_offset_set(swigCPtr, Dwg_Bitcode_3BD.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_LEADEROBJECTCONTEXTDATA_inspt_offset_get(swigCPtr);
      Dwg_Bitcode_3BD ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Bitcode_3BD(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Bitcode_3BD endptproj {
    set {
      LibreDWGPINVOKE.Dwg_Object_LEADEROBJECTCONTEXTDATA_endptproj_set(swigCPtr, Dwg_Bitcode_3BD.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_LEADEROBJECTCONTEXTDATA_endptproj_get(swigCPtr);
      Dwg_Bitcode_3BD ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Bitcode_3BD(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Object_LEADEROBJECTCONTEXTDATA() : this(LibreDWGPINVOKE.new_Dwg_Object_LEADEROBJECTCONTEXTDATA(), true) {
  }

}
