//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Dwg_HATCH_DefLine : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Dwg_HATCH_DefLine(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Dwg_HATCH_DefLine obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Dwg_HATCH_DefLine() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LibreDWGPINVOKE.delete_Dwg_HATCH_DefLine(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Dwg_Entity_HATCH parent {
    set {
      LibreDWGPINVOKE.Dwg_HATCH_DefLine_parent_set(swigCPtr, Dwg_Entity_HATCH.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_HATCH_DefLine_parent_get(swigCPtr);
      Dwg_Entity_HATCH ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Entity_HATCH(cPtr, false);
      return ret;
    } 
  }

  public double angle {
    set {
      LibreDWGPINVOKE.Dwg_HATCH_DefLine_angle_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_HATCH_DefLine_angle_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_Bitcode_2BD pt0 {
    set {
      LibreDWGPINVOKE.Dwg_HATCH_DefLine_pt0_set(swigCPtr, Dwg_Bitcode_2BD.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_HATCH_DefLine_pt0_get(swigCPtr);
      Dwg_Bitcode_2BD ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Bitcode_2BD(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Bitcode_2BD offset {
    set {
      LibreDWGPINVOKE.Dwg_HATCH_DefLine_offset_set(swigCPtr, Dwg_Bitcode_2BD.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_HATCH_DefLine_offset_get(swigCPtr);
      Dwg_Bitcode_2BD ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Bitcode_2BD(cPtr, false);
      return ret;
    } 
  }

  public ushort num_dashes {
    set {
      LibreDWGPINVOKE.Dwg_HATCH_DefLine_num_dashes_set(swigCPtr, value);
    } 
    get {
      ushort ret = LibreDWGPINVOKE.Dwg_HATCH_DefLine_num_dashes_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_double dashes {
    set {
      LibreDWGPINVOKE.Dwg_HATCH_DefLine_dashes_set(swigCPtr, SWIGTYPE_p_double.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_HATCH_DefLine_dashes_get(swigCPtr);
      SWIGTYPE_p_double ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_double(cPtr, false);
      return ret;
    } 
  }

  public Dwg_HATCH_DefLine() : this(LibreDWGPINVOKE.new_Dwg_HATCH_DefLine(), true) {
  }

}
