//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Dwg_TABLESTYLE_Cell : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Dwg_TABLESTYLE_Cell(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Dwg_TABLESTYLE_Cell obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Dwg_TABLESTYLE_Cell() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LibreDWGPINVOKE.delete_Dwg_TABLESTYLE_Cell(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Dwg_TABLE_Cell cell {
    set {
      LibreDWGPINVOKE.Dwg_TABLESTYLE_Cell_cell_set(swigCPtr, Dwg_TABLE_Cell.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_TABLESTYLE_Cell_cell_get(swigCPtr);
      Dwg_TABLE_Cell ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_TABLE_Cell(cPtr, false);
      return ret;
    } 
  }

  public uint id {
    set {
      LibreDWGPINVOKE.Dwg_TABLESTYLE_Cell_id_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_TABLESTYLE_Cell_id_get(swigCPtr);
      return ret;
    } 
  }

  public uint type {
    set {
      LibreDWGPINVOKE.Dwg_TABLESTYLE_Cell_type_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_TABLESTYLE_Cell_type_get(swigCPtr);
      return ret;
    } 
  }

  public string name {
    set {
      LibreDWGPINVOKE.Dwg_TABLESTYLE_Cell_name_set(swigCPtr, value);
    } 
    get {
      string ret = LibreDWGPINVOKE.Dwg_TABLESTYLE_Cell_name_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_Object_TABLESTYLE parent {
    set {
      LibreDWGPINVOKE.Dwg_TABLESTYLE_Cell_parent_set(swigCPtr, Dwg_Object_TABLESTYLE.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_TABLESTYLE_Cell_parent_get(swigCPtr);
      Dwg_Object_TABLESTYLE ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_TABLESTYLE(cPtr, false);
      return ret;
    } 
  }

  public Dwg_TABLESTYLE_Cell() : this(LibreDWGPINVOKE.new_Dwg_TABLESTYLE_Cell(), true) {
  }

}
