//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Dwg_Object_LAYER : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Dwg_Object_LAYER(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Dwg_Object_LAYER obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Dwg_Object_LAYER() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LibreDWGPINVOKE.delete_Dwg_Object_LAYER(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Dwg_Object_Object parent {
    set {
      LibreDWGPINVOKE.Dwg_Object_LAYER_parent_set(swigCPtr, Dwg_Object_Object.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_LAYER_parent_get(swigCPtr);
      Dwg_Object_Object ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Object(cPtr, false);
      return ret;
    } 
  }

  public ushort flag {
    set {
      LibreDWGPINVOKE.Dwg_Object_LAYER_flag_set(swigCPtr, value);
    } 
    get {
      ushort ret = LibreDWGPINVOKE.Dwg_Object_LAYER_flag_get(swigCPtr);
      return ret;
    } 
  }

  public string name {
    set {
      LibreDWGPINVOKE.Dwg_Object_LAYER_name_set(swigCPtr, value);
    } 
    get {
      string ret = LibreDWGPINVOKE.Dwg_Object_LAYER_name_get(swigCPtr);
      return ret;
    } 
  }

  public ushort used {
    set {
      LibreDWGPINVOKE.Dwg_Object_LAYER_used_set(swigCPtr, value);
    } 
    get {
      ushort ret = LibreDWGPINVOKE.Dwg_Object_LAYER_used_get(swigCPtr);
      return ret;
    } 
  }

  public byte xrefref {
    set {
      LibreDWGPINVOKE.Dwg_Object_LAYER_xrefref_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_LAYER_xrefref_get(swigCPtr);
      return ret;
    } 
  }

  public ushort xrefindex_plus1 {
    set {
      LibreDWGPINVOKE.Dwg_Object_LAYER_xrefindex_plus1_set(swigCPtr, value);
    } 
    get {
      ushort ret = LibreDWGPINVOKE.Dwg_Object_LAYER_xrefindex_plus1_get(swigCPtr);
      return ret;
    } 
  }

  public byte xrefdep {
    set {
      LibreDWGPINVOKE.Dwg_Object_LAYER_xrefdep_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_LAYER_xrefdep_get(swigCPtr);
      return ret;
    } 
  }

  public byte frozen {
    set {
      LibreDWGPINVOKE.Dwg_Object_LAYER_frozen_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_LAYER_frozen_get(swigCPtr);
      return ret;
    } 
  }

  public byte on {
    set {
      LibreDWGPINVOKE.Dwg_Object_LAYER_on_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_LAYER_on_get(swigCPtr);
      return ret;
    } 
  }

  public byte frozen_in_new {
    set {
      LibreDWGPINVOKE.Dwg_Object_LAYER_frozen_in_new_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_LAYER_frozen_in_new_get(swigCPtr);
      return ret;
    } 
  }

  public byte locked {
    set {
      LibreDWGPINVOKE.Dwg_Object_LAYER_locked_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_LAYER_locked_get(swigCPtr);
      return ret;
    } 
  }

  public byte plotflag {
    set {
      LibreDWGPINVOKE.Dwg_Object_LAYER_plotflag_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_LAYER_plotflag_get(swigCPtr);
      return ret;
    } 
  }

  public byte linewt {
    set {
      LibreDWGPINVOKE.Dwg_Object_LAYER_linewt_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_LAYER_linewt_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_Color color {
    set {
      LibreDWGPINVOKE.Dwg_Object_LAYER_color_set(swigCPtr, Dwg_Color.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_LAYER_color_get(swigCPtr);
      Dwg_Color ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Color(cPtr, false);
      return ret;
    } 
  }

  public short color_rs {
    set {
      LibreDWGPINVOKE.Dwg_Object_LAYER_color_rs_set(swigCPtr, value);
    } 
    get {
      short ret = LibreDWGPINVOKE.Dwg_Object_LAYER_color_rs_get(swigCPtr);
      return ret;
    } 
  }

  public ushort ltype_rs {
    set {
      LibreDWGPINVOKE.Dwg_Object_LAYER_ltype_rs_set(swigCPtr, value);
    } 
    get {
      ushort ret = LibreDWGPINVOKE.Dwg_Object_LAYER_ltype_rs_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_Object_Ref xref {
    set {
      LibreDWGPINVOKE.Dwg_Object_LAYER_xref_set(swigCPtr, Dwg_Object_Ref.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_LAYER_xref_get(swigCPtr);
      Dwg_Object_Ref ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Ref(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Object_Ref plotstyle {
    set {
      LibreDWGPINVOKE.Dwg_Object_LAYER_plotstyle_set(swigCPtr, Dwg_Object_Ref.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_LAYER_plotstyle_get(swigCPtr);
      Dwg_Object_Ref ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Ref(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Object_Ref material {
    set {
      LibreDWGPINVOKE.Dwg_Object_LAYER_material_set(swigCPtr, Dwg_Object_Ref.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_LAYER_material_get(swigCPtr);
      Dwg_Object_Ref ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Ref(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Object_Ref ltype {
    set {
      LibreDWGPINVOKE.Dwg_Object_LAYER_ltype_set(swigCPtr, Dwg_Object_Ref.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_LAYER_ltype_get(swigCPtr);
      Dwg_Object_Ref ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Ref(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Object_LAYER() : this(LibreDWGPINVOKE.new_Dwg_Object_LAYER(), true) {
  }

}
