//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Dwg_Section_InfoHdr : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Dwg_Section_InfoHdr(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Dwg_Section_InfoHdr obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Dwg_Section_InfoHdr() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LibreDWGPINVOKE.delete_Dwg_Section_InfoHdr(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public uint num_desc {
    set {
      LibreDWGPINVOKE.Dwg_Section_InfoHdr_num_desc_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Section_InfoHdr_num_desc_get(swigCPtr);
      return ret;
    } 
  }

  public uint compressed {
    set {
      LibreDWGPINVOKE.Dwg_Section_InfoHdr_compressed_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Section_InfoHdr_compressed_get(swigCPtr);
      return ret;
    } 
  }

  public uint max_size {
    set {
      LibreDWGPINVOKE.Dwg_Section_InfoHdr_max_size_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Section_InfoHdr_max_size_get(swigCPtr);
      return ret;
    } 
  }

  public uint encrypted {
    set {
      LibreDWGPINVOKE.Dwg_Section_InfoHdr_encrypted_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Section_InfoHdr_encrypted_get(swigCPtr);
      return ret;
    } 
  }

  public uint num_desc2 {
    set {
      LibreDWGPINVOKE.Dwg_Section_InfoHdr_num_desc2_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Section_InfoHdr_num_desc2_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_Section_InfoHdr() : this(LibreDWGPINVOKE.new_Dwg_Section_InfoHdr(), true) {
  }

}
