//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Dwg_AcDs_Data : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Dwg_AcDs_Data(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Dwg_AcDs_Data obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Dwg_AcDs_Data() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LibreDWGPINVOKE.delete_Dwg_AcDs_Data(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Dwg_AcDs_Data_RecordHdr record_hdrs {
    set {
      LibreDWGPINVOKE.Dwg_AcDs_Data_record_hdrs_set(swigCPtr, Dwg_AcDs_Data_RecordHdr.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_AcDs_Data_record_hdrs_get(swigCPtr);
      Dwg_AcDs_Data_RecordHdr ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_AcDs_Data_RecordHdr(cPtr, false);
      return ret;
    } 
  }

  public Dwg_AcDs_Data_Record records {
    set {
      LibreDWGPINVOKE.Dwg_AcDs_Data_records_set(swigCPtr, Dwg_AcDs_Data_Record.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_AcDs_Data_records_get(swigCPtr);
      Dwg_AcDs_Data_Record ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_AcDs_Data_Record(cPtr, false);
      return ret;
    } 
  }

  public Dwg_AcDs_Data() : this(LibreDWGPINVOKE.new_Dwg_AcDs_Data(), true) {
  }

}
