//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Dwg_TABLE_value : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Dwg_TABLE_value(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Dwg_TABLE_value obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Dwg_TABLE_value() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LibreDWGPINVOKE.delete_Dwg_TABLE_value(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public uint flags {
    set {
      LibreDWGPINVOKE.Dwg_TABLE_value_flags_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_TABLE_value_flags_get(swigCPtr);
      return ret;
    } 
  }

  public uint data_type {
    set {
      LibreDWGPINVOKE.Dwg_TABLE_value_data_type_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_TABLE_value_data_type_get(swigCPtr);
      return ret;
    } 
  }

  public uint data_size {
    set {
      LibreDWGPINVOKE.Dwg_TABLE_value_data_size_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_TABLE_value_data_size_get(swigCPtr);
      return ret;
    } 
  }

  public uint data_long {
    set {
      LibreDWGPINVOKE.Dwg_TABLE_value_data_long_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_TABLE_value_data_long_get(swigCPtr);
      return ret;
    } 
  }

  public double data_double {
    set {
      LibreDWGPINVOKE.Dwg_TABLE_value_data_double_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_TABLE_value_data_double_get(swigCPtr);
      return ret;
    } 
  }

  public string data_string {
    set {
      LibreDWGPINVOKE.Dwg_TABLE_value_data_string_set(swigCPtr, value);
    } 
    get {
      string ret = LibreDWGPINVOKE.Dwg_TABLE_value_data_string_get(swigCPtr);
      return ret;
    } 
  }

  public string data_date {
    set {
      LibreDWGPINVOKE.Dwg_TABLE_value_data_date_set(swigCPtr, value);
    } 
    get {
      string ret = LibreDWGPINVOKE.Dwg_TABLE_value_data_date_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_Bitcode_2RD data_point {
    set {
      LibreDWGPINVOKE.Dwg_TABLE_value_data_point_set(swigCPtr, Dwg_Bitcode_2RD.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_TABLE_value_data_point_get(swigCPtr);
      Dwg_Bitcode_2RD ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Bitcode_2RD(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Bitcode_3RD data_3dpoint {
    set {
      LibreDWGPINVOKE.Dwg_TABLE_value_data_3dpoint_set(swigCPtr, Dwg_Bitcode_3RD.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_TABLE_value_data_3dpoint_get(swigCPtr);
      Dwg_Bitcode_3RD ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Bitcode_3RD(cPtr, false);
      return ret;
    } 
  }

  public uint unit_type {
    set {
      LibreDWGPINVOKE.Dwg_TABLE_value_unit_type_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_TABLE_value_unit_type_get(swigCPtr);
      return ret;
    } 
  }

  public string format_string {
    set {
      LibreDWGPINVOKE.Dwg_TABLE_value_format_string_set(swigCPtr, value);
    } 
    get {
      string ret = LibreDWGPINVOKE.Dwg_TABLE_value_format_string_get(swigCPtr);
      return ret;
    } 
  }

  public string value_string {
    set {
      LibreDWGPINVOKE.Dwg_TABLE_value_value_string_set(swigCPtr, value);
    } 
    get {
      string ret = LibreDWGPINVOKE.Dwg_TABLE_value_value_string_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_TABLE_value() : this(LibreDWGPINVOKE.new_Dwg_TABLE_value(), true) {
  }

}
