//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Dwg_Object_BLOCKGRIPLOCATIONCOMPONENT : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Dwg_Object_BLOCKGRIPLOCATIONCOMPONENT(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Dwg_Object_BLOCKGRIPLOCATIONCOMPONENT obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Dwg_Object_BLOCKGRIPLOCATIONCOMPONENT() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LibreDWGPINVOKE.delete_Dwg_Object_BLOCKGRIPLOCATIONCOMPONENT(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Dwg_Object_Object parent {
    set {
      LibreDWGPINVOKE.Dwg_Object_BLOCKGRIPLOCATIONCOMPONENT_parent_set(swigCPtr, Dwg_Object_Object.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_BLOCKGRIPLOCATIONCOMPONENT_parent_get(swigCPtr);
      Dwg_Object_Object ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Object(cPtr, false);
      return ret;
    } 
  }

  public uint ee_bl1 {
    set {
      LibreDWGPINVOKE.Dwg_Object_BLOCKGRIPLOCATIONCOMPONENT_ee_bl1_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_BLOCKGRIPLOCATIONCOMPONENT_ee_bl1_get(swigCPtr);
      return ret;
    } 
  }

  public uint ee_bl2 {
    set {
      LibreDWGPINVOKE.Dwg_Object_BLOCKGRIPLOCATIONCOMPONENT_ee_bl2_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_BLOCKGRIPLOCATIONCOMPONENT_ee_bl2_get(swigCPtr);
      return ret;
    } 
  }

  public uint ee_bl3 {
    set {
      LibreDWGPINVOKE.Dwg_Object_BLOCKGRIPLOCATIONCOMPONENT_ee_bl3_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_BLOCKGRIPLOCATIONCOMPONENT_ee_bl3_get(swigCPtr);
      return ret;
    } 
  }

  public uint ee_bs1 {
    set {
      LibreDWGPINVOKE.Dwg_Object_BLOCKGRIPLOCATIONCOMPONENT_ee_bs1_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_BLOCKGRIPLOCATIONCOMPONENT_ee_bs1_get(swigCPtr);
      return ret;
    } 
  }

  public ushort ee_type {
    set {
      LibreDWGPINVOKE.Dwg_Object_BLOCKGRIPLOCATIONCOMPONENT_ee_type_set(swigCPtr, value);
    } 
    get {
      ushort ret = LibreDWGPINVOKE.Dwg_Object_BLOCKGRIPLOCATIONCOMPONENT_ee_type_get(swigCPtr);
      return ret;
    } 
  }

  public uint ee_bl4 {
    set {
      LibreDWGPINVOKE.Dwg_Object_BLOCKGRIPLOCATIONCOMPONENT_ee_bl4_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_BLOCKGRIPLOCATIONCOMPONENT_ee_bl4_get(swigCPtr);
      return ret;
    } 
  }

  public uint eval_type {
    set {
      LibreDWGPINVOKE.Dwg_Object_BLOCKGRIPLOCATIONCOMPONENT_eval_type_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_BLOCKGRIPLOCATIONCOMPONENT_eval_type_get(swigCPtr);
      return ret;
    } 
  }

  public string eval_expr {
    set {
      LibreDWGPINVOKE.Dwg_Object_BLOCKGRIPLOCATIONCOMPONENT_eval_expr_set(swigCPtr, value);
    } 
    get {
      string ret = LibreDWGPINVOKE.Dwg_Object_BLOCKGRIPLOCATIONCOMPONENT_eval_expr_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_Object_BLOCKGRIPLOCATIONCOMPONENT() : this(LibreDWGPINVOKE.new_Dwg_Object_BLOCKGRIPLOCATIONCOMPONENT(), true) {
  }

}
