//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum Dwg_Section_Type {
  SECTION_UNKNOWN = 0,
  SECTION_HEADER = 1,
  SECTION_AUXHEADER = 2,
  SECTION_CLASSES = 3,
  SECTION_HANDLES = 4,
  SECTION_TEMPLATE = 5,
  SECTION_OBJFREESPACE = 6,
  SECTION_OBJECTS = 7,
  SECTION_REVHISTORY = 8,
  SECTION_SUMMARYINFO = 9,
  SECTION_PREVIEW = 10,
  SECTION_APPINFO = 11,
  SECTION_APPINFOHISTORY = 12,
  SECTION_FILEDEPLIST = 13,
  SECTION_SECURITY,
  SECTION_VBAPROJECT,
  SECTION_SIGNATURE,
  SECTION_ACDS,
  SECTION_INFO,
  SECTION_SYSTEM_MAP
}
