//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Dwg_Object_MTEXTOBJECTCONTEXTDATA : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Dwg_Object_MTEXTOBJECTCONTEXTDATA(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Dwg_Object_MTEXTOBJECTCONTEXTDATA obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Dwg_Object_MTEXTOBJECTCONTEXTDATA() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LibreDWGPINVOKE.delete_Dwg_Object_MTEXTOBJECTCONTEXTDATA(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Dwg_Object_Object parent {
    set {
      LibreDWGPINVOKE.Dwg_Object_MTEXTOBJECTCONTEXTDATA_parent_set(swigCPtr, Dwg_Object_Object.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_MTEXTOBJECTCONTEXTDATA_parent_get(swigCPtr);
      Dwg_Object_Object ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Object(cPtr, false);
      return ret;
    } 
  }

  public ushort class_version {
    set {
      LibreDWGPINVOKE.Dwg_Object_MTEXTOBJECTCONTEXTDATA_class_version_set(swigCPtr, value);
    } 
    get {
      ushort ret = LibreDWGPINVOKE.Dwg_Object_MTEXTOBJECTCONTEXTDATA_class_version_get(swigCPtr);
      return ret;
    } 
  }

  public byte is_default {
    set {
      LibreDWGPINVOKE.Dwg_Object_MTEXTOBJECTCONTEXTDATA_is_default_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_MTEXTOBJECTCONTEXTDATA_is_default_get(swigCPtr);
      return ret;
    } 
  }

  public byte in_dwg {
    set {
      LibreDWGPINVOKE.Dwg_Object_MTEXTOBJECTCONTEXTDATA_in_dwg_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_MTEXTOBJECTCONTEXTDATA_in_dwg_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_Object_Ref scale {
    set {
      LibreDWGPINVOKE.Dwg_Object_MTEXTOBJECTCONTEXTDATA_scale_set(swigCPtr, Dwg_Object_Ref.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_MTEXTOBJECTCONTEXTDATA_scale_get(swigCPtr);
      Dwg_Object_Ref ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Ref(cPtr, false);
      return ret;
    } 
  }

  public ushort flag {
    set {
      LibreDWGPINVOKE.Dwg_Object_MTEXTOBJECTCONTEXTDATA_flag_set(swigCPtr, value);
    } 
    get {
      ushort ret = LibreDWGPINVOKE.Dwg_Object_MTEXTOBJECTCONTEXTDATA_flag_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_Bitcode_3BD insertion_pt {
    set {
      LibreDWGPINVOKE.Dwg_Object_MTEXTOBJECTCONTEXTDATA_insertion_pt_set(swigCPtr, Dwg_Bitcode_3BD.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_MTEXTOBJECTCONTEXTDATA_insertion_pt_get(swigCPtr);
      Dwg_Bitcode_3BD ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Bitcode_3BD(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Bitcode_3BD x_axis_dir {
    set {
      LibreDWGPINVOKE.Dwg_Object_MTEXTOBJECTCONTEXTDATA_x_axis_dir_set(swigCPtr, Dwg_Bitcode_3BD.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_MTEXTOBJECTCONTEXTDATA_x_axis_dir_get(swigCPtr);
      Dwg_Bitcode_3BD ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Bitcode_3BD(cPtr, false);
      return ret;
    } 
  }

  public double text_height {
    set {
      LibreDWGPINVOKE.Dwg_Object_MTEXTOBJECTCONTEXTDATA_text_height_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_Object_MTEXTOBJECTCONTEXTDATA_text_height_get(swigCPtr);
      return ret;
    } 
  }

  public double rect_width {
    set {
      LibreDWGPINVOKE.Dwg_Object_MTEXTOBJECTCONTEXTDATA_rect_width_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_Object_MTEXTOBJECTCONTEXTDATA_rect_width_get(swigCPtr);
      return ret;
    } 
  }

  public double rect_height {
    set {
      LibreDWGPINVOKE.Dwg_Object_MTEXTOBJECTCONTEXTDATA_rect_height_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_Object_MTEXTOBJECTCONTEXTDATA_rect_height_get(swigCPtr);
      return ret;
    } 
  }

  public double extents_height {
    set {
      LibreDWGPINVOKE.Dwg_Object_MTEXTOBJECTCONTEXTDATA_extents_height_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_Object_MTEXTOBJECTCONTEXTDATA_extents_height_get(swigCPtr);
      return ret;
    } 
  }

  public double extents_width {
    set {
      LibreDWGPINVOKE.Dwg_Object_MTEXTOBJECTCONTEXTDATA_extents_width_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_Object_MTEXTOBJECTCONTEXTDATA_extents_width_get(swigCPtr);
      return ret;
    } 
  }

  public ushort attachment {
    set {
      LibreDWGPINVOKE.Dwg_Object_MTEXTOBJECTCONTEXTDATA_attachment_set(swigCPtr, value);
    } 
    get {
      ushort ret = LibreDWGPINVOKE.Dwg_Object_MTEXTOBJECTCONTEXTDATA_attachment_get(swigCPtr);
      return ret;
    } 
  }

  public ushort drawing_dir {
    set {
      LibreDWGPINVOKE.Dwg_Object_MTEXTOBJECTCONTEXTDATA_drawing_dir_set(swigCPtr, value);
    } 
    get {
      ushort ret = LibreDWGPINVOKE.Dwg_Object_MTEXTOBJECTCONTEXTDATA_drawing_dir_get(swigCPtr);
      return ret;
    } 
  }

  public ushort linespace_style {
    set {
      LibreDWGPINVOKE.Dwg_Object_MTEXTOBJECTCONTEXTDATA_linespace_style_set(swigCPtr, value);
    } 
    get {
      ushort ret = LibreDWGPINVOKE.Dwg_Object_MTEXTOBJECTCONTEXTDATA_linespace_style_get(swigCPtr);
      return ret;
    } 
  }

  public double linespace_factor {
    set {
      LibreDWGPINVOKE.Dwg_Object_MTEXTOBJECTCONTEXTDATA_linespace_factor_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_Object_MTEXTOBJECTCONTEXTDATA_linespace_factor_get(swigCPtr);
      return ret;
    } 
  }

  public double bd45 {
    set {
      LibreDWGPINVOKE.Dwg_Object_MTEXTOBJECTCONTEXTDATA_bd45_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_Object_MTEXTOBJECTCONTEXTDATA_bd45_get(swigCPtr);
      return ret;
    } 
  }

  public ushort bs74 {
    set {
      LibreDWGPINVOKE.Dwg_Object_MTEXTOBJECTCONTEXTDATA_bs74_set(swigCPtr, value);
    } 
    get {
      ushort ret = LibreDWGPINVOKE.Dwg_Object_MTEXTOBJECTCONTEXTDATA_bs74_get(swigCPtr);
      return ret;
    } 
  }

  public double bd46 {
    set {
      LibreDWGPINVOKE.Dwg_Object_MTEXTOBJECTCONTEXTDATA_bd46_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_Object_MTEXTOBJECTCONTEXTDATA_bd46_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_Object_MTEXTOBJECTCONTEXTDATA() : this(LibreDWGPINVOKE.new_Dwg_Object_MTEXTOBJECTCONTEXTDATA(), true) {
  }

}
