//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Dwg_TableCellContent_Attr : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Dwg_TableCellContent_Attr(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Dwg_TableCellContent_Attr obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Dwg_TableCellContent_Attr() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LibreDWGPINVOKE.delete_Dwg_TableCellContent_Attr(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Dwg_Object_Ref attdef {
    set {
      LibreDWGPINVOKE.Dwg_TableCellContent_Attr_attdef_set(swigCPtr, Dwg_Object_Ref.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_TableCellContent_Attr_attdef_get(swigCPtr);
      Dwg_Object_Ref ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Ref(cPtr, false);
      return ret;
    } 
  }

  public string value {
    set {
      LibreDWGPINVOKE.Dwg_TableCellContent_Attr_value_set(swigCPtr, value);
    } 
    get {
      string ret = LibreDWGPINVOKE.Dwg_TableCellContent_Attr_value_get(swigCPtr);
      return ret;
    } 
  }

  public uint index {
    set {
      LibreDWGPINVOKE.Dwg_TableCellContent_Attr_index_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_TableCellContent_Attr_index_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_TableCellContent parent {
    set {
      LibreDWGPINVOKE.Dwg_TableCellContent_Attr_parent_set(swigCPtr, Dwg_TableCellContent.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_TableCellContent_Attr_parent_get(swigCPtr);
      Dwg_TableCellContent ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_TableCellContent(cPtr, false);
      return ret;
    } 
  }

  public Dwg_TableCellContent_Attr() : this(LibreDWGPINVOKE.new_Dwg_TableCellContent_Attr(), true) {
  }

}
