//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Dwg_Object_MENTALRAYRENDERSETTINGS : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Dwg_Object_MENTALRAYRENDERSETTINGS(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Dwg_Object_MENTALRAYRENDERSETTINGS obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Dwg_Object_MENTALRAYRENDERSETTINGS() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LibreDWGPINVOKE.delete_Dwg_Object_MENTALRAYRENDERSETTINGS(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Dwg_Object_Object parent {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_parent_set(swigCPtr, Dwg_Object_Object.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_parent_get(swigCPtr);
      Dwg_Object_Object ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Object(cPtr, false);
      return ret;
    } 
  }

  public uint class_version {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_class_version_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_class_version_get(swigCPtr);
      return ret;
    } 
  }

  public string name {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_name_set(swigCPtr, value);
    } 
    get {
      string ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_name_get(swigCPtr);
      return ret;
    } 
  }

  public byte fog_enabled {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_fog_enabled_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_fog_enabled_get(swigCPtr);
      return ret;
    } 
  }

  public byte fog_background_enabled {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_fog_background_enabled_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_fog_background_enabled_get(swigCPtr);
      return ret;
    } 
  }

  public byte backfaces_enabled {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_backfaces_enabled_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_backfaces_enabled_get(swigCPtr);
      return ret;
    } 
  }

  public byte environ_image_enabled {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_environ_image_enabled_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_environ_image_enabled_get(swigCPtr);
      return ret;
    } 
  }

  public string environ_image_filename {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_environ_image_filename_set(swigCPtr, value);
    } 
    get {
      string ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_environ_image_filename_get(swigCPtr);
      return ret;
    } 
  }

  public string description {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_description_set(swigCPtr, value);
    } 
    get {
      string ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_description_get(swigCPtr);
      return ret;
    } 
  }

  public uint display_index {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_display_index_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_display_index_get(swigCPtr);
      return ret;
    } 
  }

  public byte has_predefined {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_has_predefined_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_has_predefined_get(swigCPtr);
      return ret;
    } 
  }

  public uint mr_version {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_mr_version_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_mr_version_get(swigCPtr);
      return ret;
    } 
  }

  public uint sampling1 {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_sampling1_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_sampling1_get(swigCPtr);
      return ret;
    } 
  }

  public uint sampling2 {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_sampling2_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_sampling2_get(swigCPtr);
      return ret;
    } 
  }

  public ushort sampling_mr_filter {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_sampling_mr_filter_set(swigCPtr, value);
    } 
    get {
      ushort ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_sampling_mr_filter_get(swigCPtr);
      return ret;
    } 
  }

  public double sampling_filter1 {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_sampling_filter1_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_sampling_filter1_get(swigCPtr);
      return ret;
    } 
  }

  public double sampling_filter2 {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_sampling_filter2_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_sampling_filter2_get(swigCPtr);
      return ret;
    } 
  }

  public double sampling_contrast_color1 {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_sampling_contrast_color1_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_sampling_contrast_color1_get(swigCPtr);
      return ret;
    } 
  }

  public double sampling_contrast_color2 {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_sampling_contrast_color2_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_sampling_contrast_color2_get(swigCPtr);
      return ret;
    } 
  }

  public double sampling_contrast_color3 {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_sampling_contrast_color3_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_sampling_contrast_color3_get(swigCPtr);
      return ret;
    } 
  }

  public double sampling_contrast_color4 {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_sampling_contrast_color4_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_sampling_contrast_color4_get(swigCPtr);
      return ret;
    } 
  }

  public ushort shadow_mode {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_shadow_mode_set(swigCPtr, value);
    } 
    get {
      ushort ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_shadow_mode_get(swigCPtr);
      return ret;
    } 
  }

  public byte shadow_maps_enabled {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_shadow_maps_enabled_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_shadow_maps_enabled_get(swigCPtr);
      return ret;
    } 
  }

  public byte ray_tracing_enabled {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_ray_tracing_enabled_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_ray_tracing_enabled_get(swigCPtr);
      return ret;
    } 
  }

  public uint ray_trace_depth1 {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_ray_trace_depth1_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_ray_trace_depth1_get(swigCPtr);
      return ret;
    } 
  }

  public uint ray_trace_depth2 {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_ray_trace_depth2_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_ray_trace_depth2_get(swigCPtr);
      return ret;
    } 
  }

  public uint ray_trace_depth3 {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_ray_trace_depth3_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_ray_trace_depth3_get(swigCPtr);
      return ret;
    } 
  }

  public byte global_illumination_enabled {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_global_illumination_enabled_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_global_illumination_enabled_get(swigCPtr);
      return ret;
    } 
  }

  public uint gi_sample_count {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_gi_sample_count_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_gi_sample_count_get(swigCPtr);
      return ret;
    } 
  }

  public byte gi_sample_radius_enabled {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_gi_sample_radius_enabled_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_gi_sample_radius_enabled_get(swigCPtr);
      return ret;
    } 
  }

  public double gi_sample_radius {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_gi_sample_radius_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_gi_sample_radius_get(swigCPtr);
      return ret;
    } 
  }

  public uint gi_photons_per_light {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_gi_photons_per_light_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_gi_photons_per_light_get(swigCPtr);
      return ret;
    } 
  }

  public uint photon_trace_depth1 {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_photon_trace_depth1_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_photon_trace_depth1_get(swigCPtr);
      return ret;
    } 
  }

  public uint photon_trace_depth2 {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_photon_trace_depth2_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_photon_trace_depth2_get(swigCPtr);
      return ret;
    } 
  }

  public uint photon_trace_depth3 {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_photon_trace_depth3_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_photon_trace_depth3_get(swigCPtr);
      return ret;
    } 
  }

  public byte final_gathering_enabled {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_final_gathering_enabled_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_final_gathering_enabled_get(swigCPtr);
      return ret;
    } 
  }

  public uint fg_ray_count {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_fg_ray_count_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_fg_ray_count_get(swigCPtr);
      return ret;
    } 
  }

  public byte fg_sample_radius_state1 {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_fg_sample_radius_state1_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_fg_sample_radius_state1_get(swigCPtr);
      return ret;
    } 
  }

  public byte fg_sample_radius_state2 {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_fg_sample_radius_state2_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_fg_sample_radius_state2_get(swigCPtr);
      return ret;
    } 
  }

  public byte fg_sample_radius_state3 {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_fg_sample_radius_state3_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_fg_sample_radius_state3_get(swigCPtr);
      return ret;
    } 
  }

  public double fg_sample_radius1 {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_fg_sample_radius1_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_fg_sample_radius1_get(swigCPtr);
      return ret;
    } 
  }

  public double fg_sample_radius2 {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_fg_sample_radius2_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_fg_sample_radius2_get(swigCPtr);
      return ret;
    } 
  }

  public double light_luminance_scale {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_light_luminance_scale_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_light_luminance_scale_get(swigCPtr);
      return ret;
    } 
  }

  public ushort diagnostics_mode {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_diagnostics_mode_set(swigCPtr, value);
    } 
    get {
      ushort ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_diagnostics_mode_get(swigCPtr);
      return ret;
    } 
  }

  public ushort diagnostics_grid_mode {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_diagnostics_grid_mode_set(swigCPtr, value);
    } 
    get {
      ushort ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_diagnostics_grid_mode_get(swigCPtr);
      return ret;
    } 
  }

  public double diagnostics_grid_float {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_diagnostics_grid_float_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_diagnostics_grid_float_get(swigCPtr);
      return ret;
    } 
  }

  public ushort diagnostics_photon_mode {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_diagnostics_photon_mode_set(swigCPtr, value);
    } 
    get {
      ushort ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_diagnostics_photon_mode_get(swigCPtr);
      return ret;
    } 
  }

  public ushort diagnostics_bsp_mode {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_diagnostics_bsp_mode_set(swigCPtr, value);
    } 
    get {
      ushort ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_diagnostics_bsp_mode_get(swigCPtr);
      return ret;
    } 
  }

  public byte export_mi_enabled {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_export_mi_enabled_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_export_mi_enabled_get(swigCPtr);
      return ret;
    } 
  }

  public string mr_description {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_mr_description_set(swigCPtr, value);
    } 
    get {
      string ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_mr_description_get(swigCPtr);
      return ret;
    } 
  }

  public uint tile_size {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_tile_size_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_tile_size_get(swigCPtr);
      return ret;
    } 
  }

  public ushort tile_order {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_tile_order_set(swigCPtr, value);
    } 
    get {
      ushort ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_tile_order_get(swigCPtr);
      return ret;
    } 
  }

  public uint memory_limit {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_memory_limit_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_memory_limit_get(swigCPtr);
      return ret;
    } 
  }

  public byte diagnostics_samples_mode {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_diagnostics_samples_mode_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_diagnostics_samples_mode_get(swigCPtr);
      return ret;
    } 
  }

  public double energy_multiplier {
    set {
      LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_energy_multiplier_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_Object_MENTALRAYRENDERSETTINGS_energy_multiplier_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_Object_MENTALRAYRENDERSETTINGS() : this(LibreDWGPINVOKE.new_Dwg_Object_MENTALRAYRENDERSETTINGS(), true) {
  }

}
