//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Dwg_Object_ASSOCNETWORK : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Dwg_Object_ASSOCNETWORK(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Dwg_Object_ASSOCNETWORK obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Dwg_Object_ASSOCNETWORK() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LibreDWGPINVOKE.delete_Dwg_Object_ASSOCNETWORK(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Dwg_Object_Object parent {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCNETWORK_parent_set(swigCPtr, Dwg_Object_Object.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_ASSOCNETWORK_parent_get(swigCPtr);
      Dwg_Object_Object ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Object(cPtr, false);
      return ret;
    } 
  }

  public uint solution_status {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCNETWORK_solution_status_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_ASSOCNETWORK_solution_status_get(swigCPtr);
      return ret;
    } 
  }

  public uint geometry_status {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCNETWORK_geometry_status_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_ASSOCNETWORK_geometry_status_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_Object_Ref readdep {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCNETWORK_readdep_set(swigCPtr, Dwg_Object_Ref.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_ASSOCNETWORK_readdep_get(swigCPtr);
      Dwg_Object_Ref ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Ref(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Object_Ref writedep {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCNETWORK_writedep_set(swigCPtr, Dwg_Object_Ref.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_ASSOCNETWORK_writedep_get(swigCPtr);
      Dwg_Object_Ref ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Ref(cPtr, false);
      return ret;
    } 
  }

  public uint constraint_status {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCNETWORK_constraint_status_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_ASSOCNETWORK_constraint_status_get(swigCPtr);
      return ret;
    } 
  }

  public uint dof {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCNETWORK_dof_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_ASSOCNETWORK_dof_get(swigCPtr);
      return ret;
    } 
  }

  public byte is_body_a_proxy {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCNETWORK_is_body_a_proxy_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_ASSOCNETWORK_is_body_a_proxy_get(swigCPtr);
      return ret;
    } 
  }

  public uint unknown_assoc {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCNETWORK_unknown_assoc_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_ASSOCNETWORK_unknown_assoc_get(swigCPtr);
      return ret;
    } 
  }

  public uint unknown_n1 {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCNETWORK_unknown_n1_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_ASSOCNETWORK_unknown_n1_get(swigCPtr);
      return ret;
    } 
  }

  public uint unknown_n2 {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCNETWORK_unknown_n2_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_ASSOCNETWORK_unknown_n2_get(swigCPtr);
      return ret;
    } 
  }

  public uint num_actions {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCNETWORK_num_actions_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_ASSOCNETWORK_num_actions_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_p__dwg_object_ref actions {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCNETWORK_actions_set(swigCPtr, SWIGTYPE_p_p__dwg_object_ref.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_ASSOCNETWORK_actions_get(swigCPtr);
      SWIGTYPE_p_p__dwg_object_ref ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p__dwg_object_ref(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Object_ASSOCNETWORK() : this(LibreDWGPINVOKE.new_Dwg_Object_ASSOCNETWORK(), true) {
  }

}
