//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Dwg_Object_TVDEVICEPROPERTIES : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Dwg_Object_TVDEVICEPROPERTIES(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Dwg_Object_TVDEVICEPROPERTIES obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Dwg_Object_TVDEVICEPROPERTIES() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LibreDWGPINVOKE.delete_Dwg_Object_TVDEVICEPROPERTIES(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Dwg_Object_Object parent {
    set {
      LibreDWGPINVOKE.Dwg_Object_TVDEVICEPROPERTIES_parent_set(swigCPtr, Dwg_Object_Object.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_TVDEVICEPROPERTIES_parent_get(swigCPtr);
      Dwg_Object_Object ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Object(cPtr, false);
      return ret;
    } 
  }

  public uint flags {
    set {
      LibreDWGPINVOKE.Dwg_Object_TVDEVICEPROPERTIES_flags_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_TVDEVICEPROPERTIES_flags_get(swigCPtr);
      return ret;
    } 
  }

  public ushort max_regen_threads {
    set {
      LibreDWGPINVOKE.Dwg_Object_TVDEVICEPROPERTIES_max_regen_threads_set(swigCPtr, value);
    } 
    get {
      ushort ret = LibreDWGPINVOKE.Dwg_Object_TVDEVICEPROPERTIES_max_regen_threads_get(swigCPtr);
      return ret;
    } 
  }

  public uint use_lut_palette {
    set {
      LibreDWGPINVOKE.Dwg_Object_TVDEVICEPROPERTIES_use_lut_palette_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_TVDEVICEPROPERTIES_use_lut_palette_get(swigCPtr);
      return ret;
    } 
  }

  public ulong alt_hlt {
    set {
      LibreDWGPINVOKE.Dwg_Object_TVDEVICEPROPERTIES_alt_hlt_set(swigCPtr, value);
    } 
    get {
      ulong ret = LibreDWGPINVOKE.Dwg_Object_TVDEVICEPROPERTIES_alt_hlt_get(swigCPtr);
      return ret;
    } 
  }

  public ulong alt_hltcolor {
    set {
      LibreDWGPINVOKE.Dwg_Object_TVDEVICEPROPERTIES_alt_hltcolor_set(swigCPtr, value);
    } 
    get {
      ulong ret = LibreDWGPINVOKE.Dwg_Object_TVDEVICEPROPERTIES_alt_hltcolor_get(swigCPtr);
      return ret;
    } 
  }

  public ulong geom_shader_usage {
    set {
      LibreDWGPINVOKE.Dwg_Object_TVDEVICEPROPERTIES_geom_shader_usage_set(swigCPtr, value);
    } 
    get {
      ulong ret = LibreDWGPINVOKE.Dwg_Object_TVDEVICEPROPERTIES_geom_shader_usage_get(swigCPtr);
      return ret;
    } 
  }

  public uint blending_mode {
    set {
      LibreDWGPINVOKE.Dwg_Object_TVDEVICEPROPERTIES_blending_mode_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_TVDEVICEPROPERTIES_blending_mode_get(swigCPtr);
      return ret;
    } 
  }

  public double antialiasing_level {
    set {
      LibreDWGPINVOKE.Dwg_Object_TVDEVICEPROPERTIES_antialiasing_level_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_Object_TVDEVICEPROPERTIES_antialiasing_level_get(swigCPtr);
      return ret;
    } 
  }

  public double bd2 {
    set {
      LibreDWGPINVOKE.Dwg_Object_TVDEVICEPROPERTIES_bd2_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_Object_TVDEVICEPROPERTIES_bd2_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_Object_TVDEVICEPROPERTIES() : this(LibreDWGPINVOKE.new_Dwg_Object_TVDEVICEPROPERTIES(), true) {
  }

}
