//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Dwg_FormattedTableData : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Dwg_FormattedTableData(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Dwg_FormattedTableData obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Dwg_FormattedTableData() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LibreDWGPINVOKE.delete_Dwg_FormattedTableData(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Dwg_CellStyle cellstyle {
    set {
      LibreDWGPINVOKE.Dwg_FormattedTableData_cellstyle_set(swigCPtr, Dwg_CellStyle.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_FormattedTableData_cellstyle_get(swigCPtr);
      Dwg_CellStyle ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_CellStyle(cPtr, false);
      return ret;
    } 
  }

  public uint num_merged_cells {
    set {
      LibreDWGPINVOKE.Dwg_FormattedTableData_num_merged_cells_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_FormattedTableData_num_merged_cells_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_FormattedTableMerged merged_cells {
    set {
      LibreDWGPINVOKE.Dwg_FormattedTableData_merged_cells_set(swigCPtr, Dwg_FormattedTableMerged.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_FormattedTableData_merged_cells_get(swigCPtr);
      Dwg_FormattedTableMerged ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_FormattedTableMerged(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Object_TABLECONTENT parent {
    set {
      LibreDWGPINVOKE.Dwg_FormattedTableData_parent_set(swigCPtr, Dwg_Object_TABLECONTENT.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_FormattedTableData_parent_get(swigCPtr);
      Dwg_Object_TABLECONTENT ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_TABLECONTENT(cPtr, false);
      return ret;
    } 
  }

  public Dwg_FormattedTableData() : this(LibreDWGPINVOKE.new_Dwg_FormattedTableData(), true) {
  }

}
