//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Dwg_Object_ASSOCDEPENDENCY : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Dwg_Object_ASSOCDEPENDENCY(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Dwg_Object_ASSOCDEPENDENCY obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Dwg_Object_ASSOCDEPENDENCY() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LibreDWGPINVOKE.delete_Dwg_Object_ASSOCDEPENDENCY(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Dwg_Object_Object parent {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCDEPENDENCY_parent_set(swigCPtr, Dwg_Object_Object.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_ASSOCDEPENDENCY_parent_get(swigCPtr);
      Dwg_Object_Object ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Object(cPtr, false);
      return ret;
    } 
  }

  public uint class_version {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCDEPENDENCY_class_version_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_ASSOCDEPENDENCY_class_version_get(swigCPtr);
      return ret;
    } 
  }

  public uint status {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCDEPENDENCY_status_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_ASSOCDEPENDENCY_status_get(swigCPtr);
      return ret;
    } 
  }

  public byte isread_dep {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCDEPENDENCY_isread_dep_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_ASSOCDEPENDENCY_isread_dep_get(swigCPtr);
      return ret;
    } 
  }

  public byte iswrite_dep {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCDEPENDENCY_iswrite_dep_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_ASSOCDEPENDENCY_iswrite_dep_get(swigCPtr);
      return ret;
    } 
  }

  public byte isobjectstate_dep {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCDEPENDENCY_isobjectstate_dep_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_ASSOCDEPENDENCY_isobjectstate_dep_get(swigCPtr);
      return ret;
    } 
  }

  public byte unknown_b4 {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCDEPENDENCY_unknown_b4_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_ASSOCDEPENDENCY_unknown_b4_get(swigCPtr);
      return ret;
    } 
  }

  public uint order {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCDEPENDENCY_order_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_ASSOCDEPENDENCY_order_get(swigCPtr);
      return ret;
    } 
  }

  public byte unknown_b5 {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCDEPENDENCY_unknown_b5_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_ASSOCDEPENDENCY_unknown_b5_get(swigCPtr);
      return ret;
    } 
  }

  public uint depbodyid {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCDEPENDENCY_depbodyid_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_ASSOCDEPENDENCY_depbodyid_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_Object_Ref owner {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCDEPENDENCY_owner_set(swigCPtr, Dwg_Object_Ref.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_ASSOCDEPENDENCY_owner_get(swigCPtr);
      Dwg_Object_Ref ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Ref(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Object_Ref readdep {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCDEPENDENCY_readdep_set(swigCPtr, Dwg_Object_Ref.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_ASSOCDEPENDENCY_readdep_get(swigCPtr);
      Dwg_Object_Ref ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Ref(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Object_Ref writedep {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCDEPENDENCY_writedep_set(swigCPtr, Dwg_Object_Ref.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_ASSOCDEPENDENCY_writedep_get(swigCPtr);
      Dwg_Object_Ref ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Ref(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Object_Ref node {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCDEPENDENCY_node_set(swigCPtr, Dwg_Object_Ref.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_ASSOCDEPENDENCY_node_get(swigCPtr);
      Dwg_Object_Ref ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Ref(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Object_ASSOCDEPENDENCY() : this(LibreDWGPINVOKE.new_Dwg_Object_ASSOCDEPENDENCY(), true) {
  }

}
