//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Dwg_TABLESTYLE_rowstyles : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Dwg_TABLESTYLE_rowstyles(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Dwg_TABLESTYLE_rowstyles obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Dwg_TABLESTYLE_rowstyles() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LibreDWGPINVOKE.delete_Dwg_TABLESTYLE_rowstyles(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Dwg_Object_Ref text_style {
    set {
      LibreDWGPINVOKE.Dwg_TABLESTYLE_rowstyles_text_style_set(swigCPtr, Dwg_Object_Ref.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_TABLESTYLE_rowstyles_text_style_get(swigCPtr);
      Dwg_Object_Ref ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Ref(cPtr, false);
      return ret;
    } 
  }

  public double text_height {
    set {
      LibreDWGPINVOKE.Dwg_TABLESTYLE_rowstyles_text_height_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_TABLESTYLE_rowstyles_text_height_get(swigCPtr);
      return ret;
    } 
  }

  public ushort text_alignment {
    set {
      LibreDWGPINVOKE.Dwg_TABLESTYLE_rowstyles_text_alignment_set(swigCPtr, value);
    } 
    get {
      ushort ret = LibreDWGPINVOKE.Dwg_TABLESTYLE_rowstyles_text_alignment_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_Color text_color {
    set {
      LibreDWGPINVOKE.Dwg_TABLESTYLE_rowstyles_text_color_set(swigCPtr, Dwg_Color.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_TABLESTYLE_rowstyles_text_color_get(swigCPtr);
      Dwg_Color ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Color(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Color fill_color {
    set {
      LibreDWGPINVOKE.Dwg_TABLESTYLE_rowstyles_fill_color_set(swigCPtr, Dwg_Color.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_TABLESTYLE_rowstyles_fill_color_get(swigCPtr);
      Dwg_Color ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Color(cPtr, false);
      return ret;
    } 
  }

  public byte has_bgcolor {
    set {
      LibreDWGPINVOKE.Dwg_TABLESTYLE_rowstyles_has_bgcolor_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_TABLESTYLE_rowstyles_has_bgcolor_get(swigCPtr);
      return ret;
    } 
  }

  public uint num_borders {
    set {
      LibreDWGPINVOKE.Dwg_TABLESTYLE_rowstyles_num_borders_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_TABLESTYLE_rowstyles_num_borders_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_TABLESTYLE_border borders {
    set {
      LibreDWGPINVOKE.Dwg_TABLESTYLE_rowstyles_borders_set(swigCPtr, Dwg_TABLESTYLE_border.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_TABLESTYLE_rowstyles_borders_get(swigCPtr);
      Dwg_TABLESTYLE_border ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_TABLESTYLE_border(cPtr, false);
      return ret;
    } 
  }

  public uint data_type {
    set {
      LibreDWGPINVOKE.Dwg_TABLESTYLE_rowstyles_data_type_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_TABLESTYLE_rowstyles_data_type_get(swigCPtr);
      return ret;
    } 
  }

  public uint unit_type {
    set {
      LibreDWGPINVOKE.Dwg_TABLESTYLE_rowstyles_unit_type_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_TABLESTYLE_rowstyles_unit_type_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_unsigned_short format_string {
    set {
      LibreDWGPINVOKE.Dwg_TABLESTYLE_rowstyles_format_string_set(swigCPtr, SWIGTYPE_p_unsigned_short.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_TABLESTYLE_rowstyles_format_string_get(swigCPtr);
      SWIGTYPE_p_unsigned_short ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_short(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Object_TABLESTYLE parent {
    set {
      LibreDWGPINVOKE.Dwg_TABLESTYLE_rowstyles_parent_set(swigCPtr, Dwg_Object_TABLESTYLE.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_TABLESTYLE_rowstyles_parent_get(swigCPtr);
      Dwg_Object_TABLESTYLE ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_TABLESTYLE(cPtr, false);
      return ret;
    } 
  }

  public Dwg_TABLESTYLE_rowstyles() : this(LibreDWGPINVOKE.new_Dwg_TABLESTYLE_rowstyles(), true) {
  }

}
