//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Dwg_AcDs_DataIndex_Entry : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Dwg_AcDs_DataIndex_Entry(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Dwg_AcDs_DataIndex_Entry obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Dwg_AcDs_DataIndex_Entry() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LibreDWGPINVOKE.delete_Dwg_AcDs_DataIndex_Entry(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public uint segidx {
    set {
      LibreDWGPINVOKE.Dwg_AcDs_DataIndex_Entry_segidx_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_AcDs_DataIndex_Entry_segidx_get(swigCPtr);
      return ret;
    } 
  }

  public uint offset {
    set {
      LibreDWGPINVOKE.Dwg_AcDs_DataIndex_Entry_offset_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_AcDs_DataIndex_Entry_offset_get(swigCPtr);
      return ret;
    } 
  }

  public uint schidx {
    set {
      LibreDWGPINVOKE.Dwg_AcDs_DataIndex_Entry_schidx_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_AcDs_DataIndex_Entry_schidx_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_AcDs_DataIndex_Entry() : this(LibreDWGPINVOKE.new_Dwg_AcDs_DataIndex_Entry(), true) {
  }

}
