//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum Dwg_Version_Type {
  R_INVALID,
  R_1_1,
  R_1_2,
  R_1_4,
  R_2_0,
  R_2_1,
  R_2_5,
  R_2_6,
  R_9,
  R_10,
  R_11,
  R_13,
  R_14,
  R_2000,
  R_2004,
  R_2007,
  R_2010,
  R_2013,
  R_2018,
  R_AFTER
}
