//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Dwg_AcDs : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Dwg_AcDs(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Dwg_AcDs obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Dwg_AcDs() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LibreDWGPINVOKE.delete_Dwg_AcDs(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public uint file_signature {
    set {
      LibreDWGPINVOKE.Dwg_AcDs_file_signature_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_AcDs_file_signature_get(swigCPtr);
      return ret;
    } 
  }

  public uint file_header_size {
    set {
      LibreDWGPINVOKE.Dwg_AcDs_file_header_size_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_AcDs_file_header_size_get(swigCPtr);
      return ret;
    } 
  }

  public uint unknown_1 {
    set {
      LibreDWGPINVOKE.Dwg_AcDs_unknown_1_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_AcDs_unknown_1_get(swigCPtr);
      return ret;
    } 
  }

  public uint version {
    set {
      LibreDWGPINVOKE.Dwg_AcDs_version_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_AcDs_version_get(swigCPtr);
      return ret;
    } 
  }

  public uint unknown_2 {
    set {
      LibreDWGPINVOKE.Dwg_AcDs_unknown_2_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_AcDs_unknown_2_get(swigCPtr);
      return ret;
    } 
  }

  public uint ds_version {
    set {
      LibreDWGPINVOKE.Dwg_AcDs_ds_version_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_AcDs_ds_version_get(swigCPtr);
      return ret;
    } 
  }

  public uint segidx_offset {
    set {
      LibreDWGPINVOKE.Dwg_AcDs_segidx_offset_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_AcDs_segidx_offset_get(swigCPtr);
      return ret;
    } 
  }

  public uint segidx_unknown {
    set {
      LibreDWGPINVOKE.Dwg_AcDs_segidx_unknown_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_AcDs_segidx_unknown_get(swigCPtr);
      return ret;
    } 
  }

  public uint num_segidx {
    set {
      LibreDWGPINVOKE.Dwg_AcDs_num_segidx_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_AcDs_num_segidx_get(swigCPtr);
      return ret;
    } 
  }

  public uint schidx_segidx {
    set {
      LibreDWGPINVOKE.Dwg_AcDs_schidx_segidx_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_AcDs_schidx_segidx_get(swigCPtr);
      return ret;
    } 
  }

  public uint datidx_segidx {
    set {
      LibreDWGPINVOKE.Dwg_AcDs_datidx_segidx_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_AcDs_datidx_segidx_get(swigCPtr);
      return ret;
    } 
  }

  public uint search_segidx {
    set {
      LibreDWGPINVOKE.Dwg_AcDs_search_segidx_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_AcDs_search_segidx_get(swigCPtr);
      return ret;
    } 
  }

  public uint prvsav_segidx {
    set {
      LibreDWGPINVOKE.Dwg_AcDs_prvsav_segidx_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_AcDs_prvsav_segidx_get(swigCPtr);
      return ret;
    } 
  }

  public uint file_size {
    set {
      LibreDWGPINVOKE.Dwg_AcDs_file_size_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_AcDs_file_size_get(swigCPtr);
      return ret;
    } 
  }

  public uint total_segments {
    set {
      LibreDWGPINVOKE.Dwg_AcDs_total_segments_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_AcDs_total_segments_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_AcDs_SegmentIndex segidx {
    set {
      LibreDWGPINVOKE.Dwg_AcDs_segidx_set(swigCPtr, Dwg_AcDs_SegmentIndex.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_AcDs_segidx_get(swigCPtr);
      Dwg_AcDs_SegmentIndex ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_AcDs_SegmentIndex(cPtr, false);
      return ret;
    } 
  }

  public Dwg_AcDs_DataIndex datidx {
    set {
      LibreDWGPINVOKE.Dwg_AcDs_datidx_set(swigCPtr, Dwg_AcDs_DataIndex.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_AcDs_datidx_get(swigCPtr);
      Dwg_AcDs_DataIndex ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_AcDs_DataIndex(cPtr, false);
      return ret;
    } 
  }

  public Dwg_AcDs_Data data {
    set {
      LibreDWGPINVOKE.Dwg_AcDs_data_set(swigCPtr, Dwg_AcDs_Data.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_AcDs_data_get(swigCPtr);
      Dwg_AcDs_Data ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_AcDs_Data(cPtr, false);
      return ret;
    } 
  }

  public Dwg_AcDs_DataBlob blob01 {
    set {
      LibreDWGPINVOKE.Dwg_AcDs_blob01_set(swigCPtr, Dwg_AcDs_DataBlob.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_AcDs_blob01_get(swigCPtr);
      Dwg_AcDs_DataBlob ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_AcDs_DataBlob(cPtr, false);
      return ret;
    } 
  }

  public Dwg_AcDs_SchemaIndex schidx {
    set {
      LibreDWGPINVOKE.Dwg_AcDs_schidx_set(swigCPtr, Dwg_AcDs_SchemaIndex.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_AcDs_schidx_get(swigCPtr);
      Dwg_AcDs_SchemaIndex ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_AcDs_SchemaIndex(cPtr, false);
      return ret;
    } 
  }

  public Dwg_AcDs_SchemaData schdat {
    set {
      LibreDWGPINVOKE.Dwg_AcDs_schdat_set(swigCPtr, Dwg_AcDs_SchemaData.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_AcDs_schdat_get(swigCPtr);
      Dwg_AcDs_SchemaData ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_AcDs_SchemaData(cPtr, false);
      return ret;
    } 
  }

  public Dwg_AcDs_Search search {
    set {
      LibreDWGPINVOKE.Dwg_AcDs_search_set(swigCPtr, Dwg_AcDs_Search.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_AcDs_search_get(swigCPtr);
      Dwg_AcDs_Search ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_AcDs_Search(cPtr, false);
      return ret;
    } 
  }

  public Dwg_AcDs_Segment segments {
    set {
      LibreDWGPINVOKE.Dwg_AcDs_segments_set(swigCPtr, Dwg_AcDs_Segment.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_AcDs_segments_get(swigCPtr);
      Dwg_AcDs_Segment ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_AcDs_Segment(cPtr, false);
      return ret;
    } 
  }

  public Dwg_AcDs() : this(LibreDWGPINVOKE.new_Dwg_AcDs(), true) {
  }

}
