//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Dwg_Object_VPORT_ENTITY_HEADER : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Dwg_Object_VPORT_ENTITY_HEADER(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Dwg_Object_VPORT_ENTITY_HEADER obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Dwg_Object_VPORT_ENTITY_HEADER() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LibreDWGPINVOKE.delete_Dwg_Object_VPORT_ENTITY_HEADER(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Dwg_Object_Object parent {
    set {
      LibreDWGPINVOKE.Dwg_Object_VPORT_ENTITY_HEADER_parent_set(swigCPtr, Dwg_Object_Object.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_VPORT_ENTITY_HEADER_parent_get(swigCPtr);
      Dwg_Object_Object ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Object(cPtr, false);
      return ret;
    } 
  }

  public ushort flag {
    set {
      LibreDWGPINVOKE.Dwg_Object_VPORT_ENTITY_HEADER_flag_set(swigCPtr, value);
    } 
    get {
      ushort ret = LibreDWGPINVOKE.Dwg_Object_VPORT_ENTITY_HEADER_flag_get(swigCPtr);
      return ret;
    } 
  }

  public string name {
    set {
      LibreDWGPINVOKE.Dwg_Object_VPORT_ENTITY_HEADER_name_set(swigCPtr, value);
    } 
    get {
      string ret = LibreDWGPINVOKE.Dwg_Object_VPORT_ENTITY_HEADER_name_get(swigCPtr);
      return ret;
    } 
  }

  public ushort used {
    set {
      LibreDWGPINVOKE.Dwg_Object_VPORT_ENTITY_HEADER_used_set(swigCPtr, value);
    } 
    get {
      ushort ret = LibreDWGPINVOKE.Dwg_Object_VPORT_ENTITY_HEADER_used_get(swigCPtr);
      return ret;
    } 
  }

  public byte is_xref_ref {
    set {
      LibreDWGPINVOKE.Dwg_Object_VPORT_ENTITY_HEADER_is_xref_ref_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_VPORT_ENTITY_HEADER_is_xref_ref_get(swigCPtr);
      return ret;
    } 
  }

  public ushort is_xref_resolved {
    set {
      LibreDWGPINVOKE.Dwg_Object_VPORT_ENTITY_HEADER_is_xref_resolved_set(swigCPtr, value);
    } 
    get {
      ushort ret = LibreDWGPINVOKE.Dwg_Object_VPORT_ENTITY_HEADER_is_xref_resolved_get(swigCPtr);
      return ret;
    } 
  }

  public byte is_xref_dep {
    set {
      LibreDWGPINVOKE.Dwg_Object_VPORT_ENTITY_HEADER_is_xref_dep_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_VPORT_ENTITY_HEADER_is_xref_dep_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_Object_Ref xref {
    set {
      LibreDWGPINVOKE.Dwg_Object_VPORT_ENTITY_HEADER_xref_set(swigCPtr, Dwg_Object_Ref.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_VPORT_ENTITY_HEADER_xref_get(swigCPtr);
      Dwg_Object_Ref ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Ref(cPtr, false);
      return ret;
    } 
  }

  public byte flag1 {
    set {
      LibreDWGPINVOKE.Dwg_Object_VPORT_ENTITY_HEADER_flag1_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_VPORT_ENTITY_HEADER_flag1_get(swigCPtr);
      return ret;
    } 
  }

  public uint num_viewports {
    set {
      LibreDWGPINVOKE.Dwg_Object_VPORT_ENTITY_HEADER_num_viewports_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_VPORT_ENTITY_HEADER_num_viewports_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_p__dwg_object_ref viewports {
    set {
      LibreDWGPINVOKE.Dwg_Object_VPORT_ENTITY_HEADER_viewports_set(swigCPtr, SWIGTYPE_p_p__dwg_object_ref.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_VPORT_ENTITY_HEADER_viewports_get(swigCPtr);
      SWIGTYPE_p_p__dwg_object_ref ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p__dwg_object_ref(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Object_VPORT_ENTITY_HEADER() : this(LibreDWGPINVOKE.new_Dwg_Object_VPORT_ENTITY_HEADER(), true) {
  }

}
