//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Dwg_TABLE_CustomDataItem : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Dwg_TABLE_CustomDataItem(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Dwg_TABLE_CustomDataItem obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Dwg_TABLE_CustomDataItem() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LibreDWGPINVOKE.delete_Dwg_TABLE_CustomDataItem(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string name {
    set {
      LibreDWGPINVOKE.Dwg_TABLE_CustomDataItem_name_set(swigCPtr, value);
    } 
    get {
      string ret = LibreDWGPINVOKE.Dwg_TABLE_CustomDataItem_name_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_TABLE_value value {
    set {
      LibreDWGPINVOKE.Dwg_TABLE_CustomDataItem_value_set(swigCPtr, Dwg_TABLE_value.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_TABLE_CustomDataItem_value_get(swigCPtr);
      Dwg_TABLE_value ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_TABLE_value(cPtr, false);
      return ret;
    } 
  }

  public Dwg_TableCell cell_parent {
    set {
      LibreDWGPINVOKE.Dwg_TABLE_CustomDataItem_cell_parent_set(swigCPtr, Dwg_TableCell.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_TABLE_CustomDataItem_cell_parent_get(swigCPtr);
      Dwg_TableCell ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_TableCell(cPtr, false);
      return ret;
    } 
  }

  public Dwg_TableRow row_parent {
    set {
      LibreDWGPINVOKE.Dwg_TABLE_CustomDataItem_row_parent_set(swigCPtr, Dwg_TableRow.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_TABLE_CustomDataItem_row_parent_get(swigCPtr);
      Dwg_TableRow ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_TableRow(cPtr, false);
      return ret;
    } 
  }

  public Dwg_TABLE_CustomDataItem() : this(LibreDWGPINVOKE.new_Dwg_TABLE_CustomDataItem(), true) {
  }

}
