//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Dwg_TABLE_BreakHeight : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Dwg_TABLE_BreakHeight(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Dwg_TABLE_BreakHeight obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Dwg_TABLE_BreakHeight() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LibreDWGPINVOKE.delete_Dwg_TABLE_BreakHeight(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Dwg_Bitcode_3BD position {
    set {
      LibreDWGPINVOKE.Dwg_TABLE_BreakHeight_position_set(swigCPtr, Dwg_Bitcode_3BD.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_TABLE_BreakHeight_position_get(swigCPtr);
      Dwg_Bitcode_3BD ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Bitcode_3BD(cPtr, false);
      return ret;
    } 
  }

  public double height {
    set {
      LibreDWGPINVOKE.Dwg_TABLE_BreakHeight_height_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_TABLE_BreakHeight_height_get(swigCPtr);
      return ret;
    } 
  }

  public uint flag {
    set {
      LibreDWGPINVOKE.Dwg_TABLE_BreakHeight_flag_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_TABLE_BreakHeight_flag_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_Entity_TABLE parent {
    set {
      LibreDWGPINVOKE.Dwg_TABLE_BreakHeight_parent_set(swigCPtr, Dwg_Entity_TABLE.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_TABLE_BreakHeight_parent_get(swigCPtr);
      Dwg_Entity_TABLE ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Entity_TABLE(cPtr, false);
      return ret;
    } 
  }

  public Dwg_TABLE_BreakHeight() : this(LibreDWGPINVOKE.new_Dwg_TABLE_BreakHeight(), true) {
  }

}
