//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Dwg_FormattedTableMerged : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Dwg_FormattedTableMerged(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Dwg_FormattedTableMerged obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Dwg_FormattedTableMerged() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LibreDWGPINVOKE.delete_Dwg_FormattedTableMerged(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public uint top_row {
    set {
      LibreDWGPINVOKE.Dwg_FormattedTableMerged_top_row_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_FormattedTableMerged_top_row_get(swigCPtr);
      return ret;
    } 
  }

  public uint left_col {
    set {
      LibreDWGPINVOKE.Dwg_FormattedTableMerged_left_col_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_FormattedTableMerged_left_col_get(swigCPtr);
      return ret;
    } 
  }

  public uint bottom_row {
    set {
      LibreDWGPINVOKE.Dwg_FormattedTableMerged_bottom_row_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_FormattedTableMerged_bottom_row_get(swigCPtr);
      return ret;
    } 
  }

  public uint right_col {
    set {
      LibreDWGPINVOKE.Dwg_FormattedTableMerged_right_col_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_FormattedTableMerged_right_col_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_FormattedTableData parent {
    set {
      LibreDWGPINVOKE.Dwg_FormattedTableMerged_parent_set(swigCPtr, Dwg_FormattedTableData.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_FormattedTableMerged_parent_get(swigCPtr);
      Dwg_FormattedTableData ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_FormattedTableData(cPtr, false);
      return ret;
    } 
  }

  public Dwg_FormattedTableMerged() : this(LibreDWGPINVOKE.new_Dwg_FormattedTableMerged(), true) {
  }

}
