//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Dwg_Object_ASSOCACTION : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Dwg_Object_ASSOCACTION(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Dwg_Object_ASSOCACTION obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Dwg_Object_ASSOCACTION() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LibreDWGPINVOKE.delete_Dwg_Object_ASSOCACTION(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Dwg_Object_Object parent {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCACTION_parent_set(swigCPtr, Dwg_Object_Object.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_ASSOCACTION_parent_get(swigCPtr);
      Dwg_Object_Object ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Object(cPtr, false);
      return ret;
    } 
  }

  public uint solution_status {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCACTION_solution_status_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_ASSOCACTION_solution_status_get(swigCPtr);
      return ret;
    } 
  }

  public uint geometry_status {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCACTION_geometry_status_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_ASSOCACTION_geometry_status_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_Object_Ref readdep {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCACTION_readdep_set(swigCPtr, Dwg_Object_Ref.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_ASSOCACTION_readdep_get(swigCPtr);
      Dwg_Object_Ref ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Ref(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Object_Ref writedep {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCACTION_writedep_set(swigCPtr, Dwg_Object_Ref.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_ASSOCACTION_writedep_get(swigCPtr);
      Dwg_Object_Ref ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Ref(cPtr, false);
      return ret;
    } 
  }

  public uint constraint_status {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCACTION_constraint_status_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_ASSOCACTION_constraint_status_get(swigCPtr);
      return ret;
    } 
  }

  public uint dof {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCACTION_dof_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_ASSOCACTION_dof_get(swigCPtr);
      return ret;
    } 
  }

  public byte is_body_a_proxy {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCACTION_is_body_a_proxy_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_ASSOCACTION_is_body_a_proxy_get(swigCPtr);
      return ret;
    } 
  }

  public uint num_deps {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCACTION_num_deps_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_ASSOCACTION_num_deps_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_ACTIONBODY body {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCACTION_body_set(swigCPtr, Dwg_ACTIONBODY.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_ASSOCACTION_body_get(swigCPtr);
      Dwg_ACTIONBODY ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_ACTIONBODY(cPtr, false);
      return ret;
    } 
  }

  public uint status {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCACTION_status_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Object_ASSOCACTION_status_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_Object_Ref actionbody {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCACTION_actionbody_set(swigCPtr, Dwg_Object_Ref.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_ASSOCACTION_actionbody_get(swigCPtr);
      Dwg_Object_Ref ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Ref(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Object_Ref callback {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCACTION_callback_set(swigCPtr, Dwg_Object_Ref.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_ASSOCACTION_callback_get(swigCPtr);
      Dwg_Object_Ref ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Ref(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Object_Ref owningnetwork {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCACTION_owningnetwork_set(swigCPtr, Dwg_Object_Ref.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_ASSOCACTION_owningnetwork_get(swigCPtr);
      Dwg_Object_Ref ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Ref(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Object_ASSOCACTION() : this(LibreDWGPINVOKE.new_Dwg_Object_ASSOCACTION(), true) {
  }

}
