//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Dwg_Entity_VERTEX_2D : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Dwg_Entity_VERTEX_2D(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Dwg_Entity_VERTEX_2D obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Dwg_Entity_VERTEX_2D() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LibreDWGPINVOKE.delete_Dwg_Entity_VERTEX_2D(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Dwg_Object_Entity parent {
    set {
      LibreDWGPINVOKE.Dwg_Entity_VERTEX_2D_parent_set(swigCPtr, Dwg_Object_Entity.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Entity_VERTEX_2D_parent_get(swigCPtr);
      Dwg_Object_Entity ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Entity(cPtr, false);
      return ret;
    } 
  }

  public byte flag {
    set {
      LibreDWGPINVOKE.Dwg_Entity_VERTEX_2D_flag_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Entity_VERTEX_2D_flag_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_Bitcode_3BD point {
    set {
      LibreDWGPINVOKE.Dwg_Entity_VERTEX_2D_point_set(swigCPtr, Dwg_Bitcode_3BD.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Entity_VERTEX_2D_point_get(swigCPtr);
      Dwg_Bitcode_3BD ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Bitcode_3BD(cPtr, false);
      return ret;
    } 
  }

  public double start_width {
    set {
      LibreDWGPINVOKE.Dwg_Entity_VERTEX_2D_start_width_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_Entity_VERTEX_2D_start_width_get(swigCPtr);
      return ret;
    } 
  }

  public double end_width {
    set {
      LibreDWGPINVOKE.Dwg_Entity_VERTEX_2D_end_width_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_Entity_VERTEX_2D_end_width_get(swigCPtr);
      return ret;
    } 
  }

  public uint id {
    set {
      LibreDWGPINVOKE.Dwg_Entity_VERTEX_2D_id_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_Entity_VERTEX_2D_id_get(swigCPtr);
      return ret;
    } 
  }

  public double bulge {
    set {
      LibreDWGPINVOKE.Dwg_Entity_VERTEX_2D_bulge_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_Entity_VERTEX_2D_bulge_get(swigCPtr);
      return ret;
    } 
  }

  public double tangent_dir {
    set {
      LibreDWGPINVOKE.Dwg_Entity_VERTEX_2D_tangent_dir_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_Entity_VERTEX_2D_tangent_dir_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_Entity_VERTEX_2D() : this(LibreDWGPINVOKE.new_Dwg_Entity_VERTEX_2D(), true) {
  }

}
