//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Dwg_Object_ASSOCGEOMDEPENDENCY : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Dwg_Object_ASSOCGEOMDEPENDENCY(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Dwg_Object_ASSOCGEOMDEPENDENCY obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Dwg_Object_ASSOCGEOMDEPENDENCY() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LibreDWGPINVOKE.delete_Dwg_Object_ASSOCGEOMDEPENDENCY(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Dwg_Object_Object parent {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCGEOMDEPENDENCY_parent_set(swigCPtr, Dwg_Object_Object.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_ASSOCGEOMDEPENDENCY_parent_get(swigCPtr);
      Dwg_Object_Object ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Object(cPtr, false);
      return ret;
    } 
  }

  public ushort class_version {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCGEOMDEPENDENCY_class_version_set(swigCPtr, value);
    } 
    get {
      ushort ret = LibreDWGPINVOKE.Dwg_Object_ASSOCGEOMDEPENDENCY_class_version_get(swigCPtr);
      return ret;
    } 
  }

  public ushort dependent_on_object_status {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCGEOMDEPENDENCY_dependent_on_object_status_set(swigCPtr, value);
    } 
    get {
      ushort ret = LibreDWGPINVOKE.Dwg_Object_ASSOCGEOMDEPENDENCY_dependent_on_object_status_get(swigCPtr);
      return ret;
    } 
  }

  public byte has_cached_value {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCGEOMDEPENDENCY_has_cached_value_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_ASSOCGEOMDEPENDENCY_has_cached_value_get(swigCPtr);
      return ret;
    } 
  }

  public byte is_actionevaluation_in_progress {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCGEOMDEPENDENCY_is_actionevaluation_in_progress_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_ASSOCGEOMDEPENDENCY_is_actionevaluation_in_progress_get(swigCPtr);
      return ret;
    } 
  }

  public byte is_attached_to_object {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCGEOMDEPENDENCY_is_attached_to_object_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_ASSOCGEOMDEPENDENCY_is_attached_to_object_get(swigCPtr);
      return ret;
    } 
  }

  public byte is_delegating_to_owning_action {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCGEOMDEPENDENCY_is_delegating_to_owning_action_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_ASSOCGEOMDEPENDENCY_is_delegating_to_owning_action_get(swigCPtr);
      return ret;
    } 
  }

  public ushort bs90_2 {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCGEOMDEPENDENCY_bs90_2_set(swigCPtr, value);
    } 
    get {
      ushort ret = LibreDWGPINVOKE.Dwg_Object_ASSOCGEOMDEPENDENCY_bs90_2_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_Object_Ref h330_1 {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCGEOMDEPENDENCY_h330_1_set(swigCPtr, Dwg_Object_Ref.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_ASSOCGEOMDEPENDENCY_h330_1_get(swigCPtr);
      Dwg_Object_Ref ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Ref(cPtr, false);
      return ret;
    } 
  }

  public byte b290_5 {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCGEOMDEPENDENCY_b290_5_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_ASSOCGEOMDEPENDENCY_b290_5_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_Object_Ref h330_2 {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCGEOMDEPENDENCY_h330_2_set(swigCPtr, Dwg_Object_Ref.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_ASSOCGEOMDEPENDENCY_h330_2_get(swigCPtr);
      Dwg_Object_Ref ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Ref(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Object_Ref h330_3 {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCGEOMDEPENDENCY_h330_3_set(swigCPtr, Dwg_Object_Ref.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_ASSOCGEOMDEPENDENCY_h330_3_get(swigCPtr);
      Dwg_Object_Ref ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Ref(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Object_Ref h360 {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCGEOMDEPENDENCY_h360_set(swigCPtr, Dwg_Object_Ref.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_Object_ASSOCGEOMDEPENDENCY_h360_get(swigCPtr);
      Dwg_Object_Ref ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Object_Ref(cPtr, false);
      return ret;
    } 
  }

  public ushort bs90_3 {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCGEOMDEPENDENCY_bs90_3_set(swigCPtr, value);
    } 
    get {
      ushort ret = LibreDWGPINVOKE.Dwg_Object_ASSOCGEOMDEPENDENCY_bs90_3_get(swigCPtr);
      return ret;
    } 
  }

  public ushort bs90_4 {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCGEOMDEPENDENCY_bs90_4_set(swigCPtr, value);
    } 
    get {
      ushort ret = LibreDWGPINVOKE.Dwg_Object_ASSOCGEOMDEPENDENCY_bs90_4_get(swigCPtr);
      return ret;
    } 
  }

  public byte b290_6 {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCGEOMDEPENDENCY_b290_6_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_ASSOCGEOMDEPENDENCY_b290_6_get(swigCPtr);
      return ret;
    } 
  }

  public string t {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCGEOMDEPENDENCY_t_set(swigCPtr, value);
    } 
    get {
      string ret = LibreDWGPINVOKE.Dwg_Object_ASSOCGEOMDEPENDENCY_t_get(swigCPtr);
      return ret;
    } 
  }

  public byte dependent_on_compound_object {
    set {
      LibreDWGPINVOKE.Dwg_Object_ASSOCGEOMDEPENDENCY_dependent_on_compound_object_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_Object_ASSOCGEOMDEPENDENCY_dependent_on_compound_object_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_Object_ASSOCGEOMDEPENDENCY() : this(LibreDWGPINVOKE.new_Dwg_Object_ASSOCGEOMDEPENDENCY(), true) {
  }

}
