//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Dwg_HATCH_PathSeg : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Dwg_HATCH_PathSeg(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Dwg_HATCH_PathSeg obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Dwg_HATCH_PathSeg() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LibreDWGPINVOKE.delete_Dwg_HATCH_PathSeg(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Dwg_HATCH_Path parent {
    set {
      LibreDWGPINVOKE.Dwg_HATCH_PathSeg_parent_set(swigCPtr, Dwg_HATCH_Path.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_HATCH_PathSeg_parent_get(swigCPtr);
      Dwg_HATCH_Path ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_HATCH_Path(cPtr, false);
      return ret;
    } 
  }

  public byte type_status {
    set {
      LibreDWGPINVOKE.Dwg_HATCH_PathSeg_type_status_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_HATCH_PathSeg_type_status_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_Bitcode_2RD first_endpoint {
    set {
      LibreDWGPINVOKE.Dwg_HATCH_PathSeg_first_endpoint_set(swigCPtr, Dwg_Bitcode_2RD.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_HATCH_PathSeg_first_endpoint_get(swigCPtr);
      Dwg_Bitcode_2RD ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Bitcode_2RD(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Bitcode_2RD second_endpoint {
    set {
      LibreDWGPINVOKE.Dwg_HATCH_PathSeg_second_endpoint_set(swigCPtr, Dwg_Bitcode_2RD.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_HATCH_PathSeg_second_endpoint_get(swigCPtr);
      Dwg_Bitcode_2RD ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Bitcode_2RD(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Bitcode_2RD center {
    set {
      LibreDWGPINVOKE.Dwg_HATCH_PathSeg_center_set(swigCPtr, Dwg_Bitcode_2RD.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_HATCH_PathSeg_center_get(swigCPtr);
      Dwg_Bitcode_2RD ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Bitcode_2RD(cPtr, false);
      return ret;
    } 
  }

  public double radius {
    set {
      LibreDWGPINVOKE.Dwg_HATCH_PathSeg_radius_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_HATCH_PathSeg_radius_get(swigCPtr);
      return ret;
    } 
  }

  public double start_angle {
    set {
      LibreDWGPINVOKE.Dwg_HATCH_PathSeg_start_angle_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_HATCH_PathSeg_start_angle_get(swigCPtr);
      return ret;
    } 
  }

  public double end_angle {
    set {
      LibreDWGPINVOKE.Dwg_HATCH_PathSeg_end_angle_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_HATCH_PathSeg_end_angle_get(swigCPtr);
      return ret;
    } 
  }

  public byte is_ccw {
    set {
      LibreDWGPINVOKE.Dwg_HATCH_PathSeg_is_ccw_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_HATCH_PathSeg_is_ccw_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_Bitcode_2RD endpoint {
    set {
      LibreDWGPINVOKE.Dwg_HATCH_PathSeg_endpoint_set(swigCPtr, Dwg_Bitcode_2RD.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_HATCH_PathSeg_endpoint_get(swigCPtr);
      Dwg_Bitcode_2RD ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Bitcode_2RD(cPtr, false);
      return ret;
    } 
  }

  public double minor_major_ratio {
    set {
      LibreDWGPINVOKE.Dwg_HATCH_PathSeg_minor_major_ratio_set(swigCPtr, value);
    } 
    get {
      double ret = LibreDWGPINVOKE.Dwg_HATCH_PathSeg_minor_major_ratio_get(swigCPtr);
      return ret;
    } 
  }

  public uint degree {
    set {
      LibreDWGPINVOKE.Dwg_HATCH_PathSeg_degree_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_HATCH_PathSeg_degree_get(swigCPtr);
      return ret;
    } 
  }

  public byte is_rational {
    set {
      LibreDWGPINVOKE.Dwg_HATCH_PathSeg_is_rational_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_HATCH_PathSeg_is_rational_get(swigCPtr);
      return ret;
    } 
  }

  public byte is_periodic {
    set {
      LibreDWGPINVOKE.Dwg_HATCH_PathSeg_is_periodic_set(swigCPtr, value);
    } 
    get {
      byte ret = LibreDWGPINVOKE.Dwg_HATCH_PathSeg_is_periodic_get(swigCPtr);
      return ret;
    } 
  }

  public uint num_knots {
    set {
      LibreDWGPINVOKE.Dwg_HATCH_PathSeg_num_knots_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_HATCH_PathSeg_num_knots_get(swigCPtr);
      return ret;
    } 
  }

  public uint num_control_points {
    set {
      LibreDWGPINVOKE.Dwg_HATCH_PathSeg_num_control_points_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_HATCH_PathSeg_num_control_points_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_double knots {
    set {
      LibreDWGPINVOKE.Dwg_HATCH_PathSeg_knots_set(swigCPtr, SWIGTYPE_p_double.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_HATCH_PathSeg_knots_get(swigCPtr);
      SWIGTYPE_p_double ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_double(cPtr, false);
      return ret;
    } 
  }

  public Dwg_HATCH_ControlPoint control_points {
    set {
      LibreDWGPINVOKE.Dwg_HATCH_PathSeg_control_points_set(swigCPtr, Dwg_HATCH_ControlPoint.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_HATCH_PathSeg_control_points_get(swigCPtr);
      Dwg_HATCH_ControlPoint ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_HATCH_ControlPoint(cPtr, false);
      return ret;
    } 
  }

  public uint num_fitpts {
    set {
      LibreDWGPINVOKE.Dwg_HATCH_PathSeg_num_fitpts_set(swigCPtr, value);
    } 
    get {
      uint ret = LibreDWGPINVOKE.Dwg_HATCH_PathSeg_num_fitpts_get(swigCPtr);
      return ret;
    } 
  }

  public Dwg_Bitcode_2RD fitpts {
    set {
      LibreDWGPINVOKE.Dwg_HATCH_PathSeg_fitpts_set(swigCPtr, Dwg_Bitcode_2RD.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_HATCH_PathSeg_fitpts_get(swigCPtr);
      Dwg_Bitcode_2RD ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Bitcode_2RD(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Bitcode_2RD start_tangent {
    set {
      LibreDWGPINVOKE.Dwg_HATCH_PathSeg_start_tangent_set(swigCPtr, Dwg_Bitcode_2RD.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_HATCH_PathSeg_start_tangent_get(swigCPtr);
      Dwg_Bitcode_2RD ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Bitcode_2RD(cPtr, false);
      return ret;
    } 
  }

  public Dwg_Bitcode_2RD end_tangent {
    set {
      LibreDWGPINVOKE.Dwg_HATCH_PathSeg_end_tangent_set(swigCPtr, Dwg_Bitcode_2RD.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.Dwg_HATCH_PathSeg_end_tangent_get(swigCPtr);
      Dwg_Bitcode_2RD ret = (cPtr == global::System.IntPtr.Zero) ? null : new Dwg_Bitcode_2RD(cPtr, false);
      return ret;
    } 
  }

  public Dwg_HATCH_PathSeg() : this(LibreDWGPINVOKE.new_Dwg_HATCH_PathSeg(), true) {
  }

}
