//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class eed_data_t : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal eed_data_t(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(eed_data_t obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~eed_data_t() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LibreDWGPINVOKE.delete_eed_data_t(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public eed_data_t_eed_0 eed_0 {
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.eed_data_t_eed_0_get(swigCPtr);
      eed_data_t_eed_0 ret = (cPtr == global::System.IntPtr.Zero) ? null : new eed_data_t_eed_0(cPtr, false);
      return ret;
    } 
  }

  public eed_data_t_eed_0_r2007 eed_0_r2007 {
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.eed_data_t_eed_0_r2007_get(swigCPtr);
      eed_data_t_eed_0_r2007 ret = (cPtr == global::System.IntPtr.Zero) ? null : new eed_data_t_eed_0_r2007(cPtr, false);
      return ret;
    } 
  }

  public eed_data_t_eed_1 eed_1 {
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.eed_data_t_eed_1_get(swigCPtr);
      eed_data_t_eed_1 ret = (cPtr == global::System.IntPtr.Zero) ? null : new eed_data_t_eed_1(cPtr, false);
      return ret;
    } 
  }

  public eed_data_t_eed_2 eed_2 {
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.eed_data_t_eed_2_get(swigCPtr);
      eed_data_t_eed_2 ret = (cPtr == global::System.IntPtr.Zero) ? null : new eed_data_t_eed_2(cPtr, false);
      return ret;
    } 
  }

  public eed_data_t_eed_3 eed_3 {
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.eed_data_t_eed_3_get(swigCPtr);
      eed_data_t_eed_3 ret = (cPtr == global::System.IntPtr.Zero) ? null : new eed_data_t_eed_3(cPtr, false);
      return ret;
    } 
  }

  public eed_data_t_eed_4 eed_4 {
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.eed_data_t_eed_4_get(swigCPtr);
      eed_data_t_eed_4 ret = (cPtr == global::System.IntPtr.Zero) ? null : new eed_data_t_eed_4(cPtr, false);
      return ret;
    } 
  }

  public eed_data_t_eed_5 eed_5 {
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.eed_data_t_eed_5_get(swigCPtr);
      eed_data_t_eed_5 ret = (cPtr == global::System.IntPtr.Zero) ? null : new eed_data_t_eed_5(cPtr, false);
      return ret;
    } 
  }

  public eed_data_t_eed_10 eed_10 {
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.eed_data_t_eed_10_get(swigCPtr);
      eed_data_t_eed_10 ret = (cPtr == global::System.IntPtr.Zero) ? null : new eed_data_t_eed_10(cPtr, false);
      return ret;
    } 
  }

  public eed_data_t_eed_40 eed_40 {
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.eed_data_t_eed_40_get(swigCPtr);
      eed_data_t_eed_40 ret = (cPtr == global::System.IntPtr.Zero) ? null : new eed_data_t_eed_40(cPtr, false);
      return ret;
    } 
  }

  public eed_data_t_eed_70 eed_70 {
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.eed_data_t_eed_70_get(swigCPtr);
      eed_data_t_eed_70 ret = (cPtr == global::System.IntPtr.Zero) ? null : new eed_data_t_eed_70(cPtr, false);
      return ret;
    } 
  }

  public eed_data_t_eed_71 eed_71 {
    get {
      global::System.IntPtr cPtr = LibreDWGPINVOKE.eed_data_t_eed_71_get(swigCPtr);
      eed_data_t_eed_71 ret = (cPtr == global::System.IntPtr.Zero) ? null : new eed_data_t_eed_71(cPtr, false);
      return ret;
    } 
  }

  public eed_data_t() : this(LibreDWGPINVOKE.new_eed_data_t(), true) {
  }

}
